const themesData = [
  {
    id: 1,
    title: '1) 시간과 날짜\n(Thời gian & Ngày tháng)',
    icon: '⏰',
    words: [
      { kr: '오늘', pr: 'O-neul', vn: 'Hôm nay' },
      { kr: '내일', pr: 'Nae-il', vn: 'Ngày mai' },
      { kr: '어제', pr: 'Eo-je', vn: 'Hôm qua' },
      { kr: '지금', pr: 'Ji-geum', vn: 'Bây giờ' },
      { kr: '아침', pr: 'A-chim', vn: 'Buổi sáng' },
      { kr: '점심', pr: 'Jeom-sim', vn: 'Buổi trưa' },
      { kr: '저녁', pr: 'Jeo-nyeok', vn: 'Buổi tối' },
      { kr: '주말', pr: 'Ju-mal', vn: 'Cuối tuần' },
      { kr: '시간', pr: 'Si-gan', vn: 'Thời gian' },
      { kr: '약속', pr: 'Yak-sok', vn: 'Cuộc hẹn / Lời hứa' },
      { kr: '년', pr: 'Nyeon', vn: 'Năm' },
      { kr: '월', pr: 'Wol', vn: 'Tháng' },
      { kr: '일', pr: 'Il', vn: 'Ngày' },
      { kr: '시', pr: 'Si', vn: 'Giờ' },
      { kr: '분', pr: 'Bun', vn: 'Phút' },
      { kr: '초', pr: 'Cho', vn: 'Giây' },
      { kr: '주', pr: 'Ju', vn: 'Tuần' },
      { kr: '달', pr: 'Dal', vn: 'Tháng' },
      { kr: '평일', pr: 'Pyeong-il', vn: 'Ngày thường' },
      { kr: '새벽', pr: 'Sae-byeok', vn: 'Rạng sáng' },
      { kr: '밤', pr: 'Bam', vn: 'Đêm' },
      { kr: '낮', pr: 'Nat', vn: 'Ban ngày' },
      { kr: '봄', pr: 'Bom', vn: 'Mùa xuân' },
      { kr: '여름', pr: 'Yeo-reum', vn: 'Mùa hè' },
      { kr: '가을', pr: 'Ga-eul', vn: 'Mùa thu' },
      { kr: '겨울', pr: 'Gyeo-ul', vn: 'Mùa đông' },
      { kr: '작년', pr: 'Jak-nyeon', vn: 'Năm ngoái' },
      { kr: '올해', pr: 'Ol-hae', vn: 'Năm nay' },
      { kr: '내년', pr: 'Nae-nyeon', vn: 'Năm sau' },
      { kr: '지난달', pr: 'Ji-nan-dal', vn: 'Tháng trước' },
      { kr: '이번달', pr: 'I-beon-dal', vn: 'Tháng này' },
      { kr: '다음달', pr: 'Da-eum-dal', vn: 'Tháng sau' },
      { kr: '지난주', pr: 'Ji-nan-ju', vn: 'Tuần trước' },
      { kr: '이번주', pr: 'I-beon-ju', vn: 'Tuần này' },
      { kr: '다음주', pr: 'Da-eum-ju', vn: 'Tuần sau' },
      { kr: '언제', pr: 'Eon-je', vn: 'Khi nào' },
      { kr: '일찍', pr: 'Il-jjik', vn: 'Sớm' },
      { kr: '늦게', pr: 'Neut-ge', vn: 'Muộn' },
      { kr: '항상', pr: 'Hang-sang', vn: 'Luôn luôn' },
      { kr: '가끔', pr: 'Ga-ggeum', vn: 'Thỉnh thoảng' },
      { kr: '자주', pr: 'Ja-ju', vn: 'Thường xuyên' },
      { kr: '방금', pr: 'Bang-geum', vn: 'Vừa mới' },
      { kr: '아까', pr: 'A-kka', vn: 'Lúc nãy' },
      { kr: '나중에', pr: 'Na-jung-e', vn: 'Sau này' },
      { kr: '이따가', pr: 'I-tta-ga', vn: 'Lát nữa' },
      { kr: '매일', pr: 'Mae-il', vn: 'Mỗi ngày' },
      { kr: '매주', pr: 'Mae-ju', vn: 'Mỗi tuần' },
      { kr: '매월', pr: 'Mae-wol', vn: 'Mỗi tháng' },
      { kr: '매년', pr: 'Mae-nyeon', vn: 'Mỗi năm' },
      { kr: '종일', pr: 'Jong-il', vn: 'Cả ngày' },
    ],
  },
  {
    id: 2,
    title: '2) 장소와 방향\n(Địa điểm & Phương hướng)',
    icon: '🗺️',
    words: [
      { kr: '학교', pr: 'Hak-gyo', vn: 'Trường học' },
      { kr: '회사', pr: 'Hoe-sa', vn: 'Công ty' },
      { kr: '집', pr: 'Jip', vn: 'Nhà' },
      { kr: '병원', pr: 'Byeong-won', vn: 'Bệnh viện' },
      { kr: '은행', pr: 'Eun-haeng', vn: 'Ngân hàng' },
      { kr: '식당', pr: 'Sik-dang', vn: 'Nhà hàng / Quán ăn' },
      { kr: '앞', pr: 'Ap', vn: 'Phía trước' },
      { kr: '뒤', pr: 'Dwi', vn: 'Phía sau' },
      { kr: '옆', pr: 'Yeop', vn: 'Bên cạnh' },
      { kr: '근처', pr: 'Geun-cheo', vn: 'Gần đây' },
      { kr: '위', pr: 'Wi', vn: 'Bên trên' },
      { kr: '아래', pr: 'A-rae', vn: 'Bên dưới' },
      { kr: '안', pr: 'An', vn: 'Bên trong' },
      { kr: '밖', pr: 'Bak', vn: 'Bên ngoài' },
      { kr: '오른쪽', pr: 'O-reun-jjok', vn: 'Bên phải' },
      { kr: '왼쪽', pr: 'Oen-jjok', vn: 'Bên trái' },
      { kr: '건너편', pr: 'Geon-neo-pyeon', vn: 'Phía đối diện' },
      { kr: '똑바로', pr: 'Ttok-ba-ro', vn: 'Đi thẳng' },
      { kr: '시장', pr: 'Si-jang', vn: 'Chợ' },
      { kr: '마트', pr: 'Ma-teu', vn: 'Siêu thị' },
      { kr: '편의점', pr: 'Pyeon-ui-jeom', vn: 'Cửa hàng tiện lợi' },
      { kr: '백화점', pr: 'Baek-hwa-jeom', vn: 'Trung tâm thương mại' },
      { kr: '약국', pr: 'Yak-guk', vn: 'Hiệu thuốc' },
      { kr: '우체국', pr: 'U-che-guk', vn: 'Bưu điện' },
      { kr: '경찰서', pr: 'Gyeong-chal-seo', vn: 'Đồn cảnh sát' },
      { kr: '소방서', pr: 'So-bang-seo', vn: 'Trạm cứu hỏa' },
      { kr: '공원', pr: 'Gong-won', vn: 'Công viên' },
      { kr: '산', pr: 'San', vn: 'Núi' },
      { kr: '바다', pr: 'Ba-da', vn: 'Biển' },
      { kr: '강', pr: 'Gang', vn: 'Sông' },
      { kr: '호수', pr: 'Ho-su', vn: 'Hồ' },
      { kr: '카페', pr: 'Ka-pe', vn: 'Quán cà phê' },
      { kr: '빵집', pr: 'Ppang-jip', vn: 'Tiệm bánh mì' },
      { kr: '서점', pr: 'Seo-jeom', vn: 'Hiệu sách' },
      { kr: '도서관', pr: 'Do-seo-gwan', vn: 'Thư viện' },
      { kr: '영화관', pr: 'Yeong-hwa-gwan', vn: 'Rạp chiếu phim' },
      { kr: '극장', pr: 'Geuk-jang', vn: 'Nhà hát' },
      { kr: '노래방', pr: 'No-rae-bang', vn: 'Quán Karaoke' },
      { kr: '미용실', pr: 'Mi-yong-sil', vn: 'Tiệm làm tóc' },
      { kr: '세탁소', pr: 'Se-tak-so', vn: 'Tiệm giặt ủi' },
      { kr: '화장실', pr: 'Hwa-jang-sil', vn: 'Nhà vệ sinh' },
      { kr: '방', pr: 'Bang', vn: 'Phòng' },
      { kr: '거실', pr: 'Geo-sil', vn: 'Phòng khách' },
      { kr: '부엌', pr: 'Bu-eok', vn: 'Phòng bếp' },
      { kr: '계단', pr: 'Gye-dan', vn: 'Cầu thang' },
      { kr: '엘리베이터', pr: 'El-ri-be-i-teo', vn: 'Thang máy' },
      { kr: '주차장', pr: 'Ju-cha-jang', vn: 'Bãi đỗ xe' },
      { kr: '버스터미널', pr: 'Beo-seu-teo-mi-neol', vn: 'Bến xe buýt' },
      { kr: '기차역', pr: 'Gi-cha-yeok', vn: 'Ga tàu hỏa' },
      { kr: '공항', pr: 'Gong-hang', vn: 'Sân bay' },
    ],
  },
  {
    id: 3,
    title: '3) 필수 동사\n(Động từ cơ bản)',
    icon: '🏃',
    words: [
      { kr: '가다', pr: 'Ga-da', vn: 'Đi' },
      { kr: '오다', pr: 'O-da', vn: 'Đến' },
      { kr: '먹다', pr: 'Meok-da', vn: 'Ăn' },
      { kr: '마시다', pr: 'Ma-si-da', vn: 'Uống' },
      { kr: '자다', pr: 'Ja-da', vn: 'Ngủ' },
      { kr: '일하다', pr: 'Il-ha-da', vn: 'Làm việc' },
      { kr: '공부하다', pr: 'Gong-bu-ha-da', vn: 'Học bài' },
      { kr: '만나다', pr: 'Man-na-da', vn: 'Gặp gỡ' },
      { kr: '사다', pr: 'Sa-da', vn: 'Mua' },
      { kr: '보다', pr: 'Bo-da', vn: 'Xem / Nhìn' },
      { kr: '듣다', pr: 'Deut-da', vn: 'Nghe' },
      { kr: '읽다', pr: 'Ik-da', vn: 'Đọc' },
      { kr: '쓰다', pr: 'Sseu-da', vn: 'Viết / Đội' },
      { kr: '말하다', pr: 'Mal-ha-da', vn: 'Nói' },
      { kr: '쉬다', pr: 'Swi-da', vn: 'Nghỉ ngơi' },
      { kr: '놀다', pr: 'Nol-da', vn: 'Chơi' },
      { kr: '운동하다', pr: 'Un-dong-ha-da', vn: 'Tập thể dục' },
      { kr: '타다', pr: 'Ta-da', vn: 'Lên xe / Cưỡi' },
      { kr: '내리다', pr: 'Nae-ri-da', vn: 'Xuống xe' },
      { kr: '걷다', pr: 'Geot-da', vn: 'Đi bộ' },
      { kr: '뛰다', pr: 'Ttwi-da', vn: 'Chạy / Nhảy' },
      { kr: '입다', pr: 'Ip-da', vn: 'Mặc' },
      { kr: '벗다', pr: 'Beot-da', vn: 'Cởi' },
      { kr: '신다', pr: 'Sin-da', vn: 'Đi giày' },
      { kr: '씻다', pr: 'Ssit-da', vn: 'Rửa / Tắm' },
      { kr: '닦다', pr: 'Dak-da', vn: 'Lau chùi' },
      { kr: '만들다', pr: 'Man-deul-da', vn: 'Làm / Chế tạo' },
      { kr: '요리하다', pr: 'Yo-ri-ha-da', vn: 'Nấu ăn' },
      { kr: '주다', pr: 'Ju-da', vn: 'Cho / Đưa' },
      { kr: '받다', pr: 'Bat-da', vn: 'Nhận' },
      { kr: '빌리다', pr: 'Bil-ri-da', vn: 'Mượn' },
      { kr: '빌려주다', pr: 'Bil-ryeo-ju-da', vn: 'Cho mượn' },
      { kr: '묻다', pr: 'Mut-da', vn: 'Hỏi' },
      { kr: '대답하다', pr: 'Dae-dap-ha-da', vn: 'Trả lời' },
      { kr: '알다', pr: 'Al-da', vn: 'Biết' },
      { kr: '모르다', pr: 'Mo-reu-da', vn: 'Không biết' },
      { kr: '좋아하다', pr: 'Jo-a-ha-da', vn: 'Thích' },
      { kr: '싫어하다', pr: 'Sil-eo-ha-da', vn: 'Ghét' },
      { kr: '사랑하다', pr: 'Sa-rang-ha-da', vn: 'Yêu' },
      { kr: '생각하다', pr: 'Saeng-gak-ha-da', vn: 'Suy nghĩ' },
      { kr: '기다리다', pr: 'Gi-da-ri-da', vn: 'Chờ đợi' },
      { kr: '찾다', pr: 'Chat-da', vn: 'Tìm kiếm' },
      { kr: '잃어버리다', pr: 'Il-eo-beo-ri-da', vn: 'Làm mất' },
      { kr: '열다', pr: 'Yeol-da', vn: 'Mở' },
      { kr: '닫다', pr: 'Dat-da', vn: 'Đóng' },
      { kr: '켜다', pr: 'Kyeo-da', vn: 'Bật' },
      { kr: '끄다', pr: 'Kkeu-da', vn: 'Tắt' },
      { kr: '시작하다', pr: 'Si-jak-ha-da', vn: 'Bắt đầu' },
      { kr: '끝나다', pr: 'Kkeut-na-da', vn: 'Kết thúc' },
      { kr: '살다', pr: 'Sal-da', vn: 'Sống' },
    ],
  },
  {
    id: 4,
    title: '4) 음식과 맛\n(Đồ ăn & Mùi vị)',
    icon: '🍜',
    words: [
      { kr: '밥', pr: 'Bap', vn: 'Cơm' },
      { kr: '물', pr: 'Mul', vn: 'Nước' },
      { kr: '고기', pr: 'Go-gi', vn: 'Thịt' },
      { kr: '과일', pr: 'Gwa-il', vn: 'Trái cây' },
      { kr: '우유', pr: 'U-yu', vn: 'Sữa' },
      { kr: '빵', pr: 'Ppang', vn: 'Bánh mì' },
      { kr: '맛있다', pr: 'Ma-sit-da', vn: 'Ngon' },
      { kr: '맛없다', pr: 'Ma-seop-da', vn: 'Không ngon' },
      { kr: '맵다', pr: 'Maep-da', vn: 'Cay' },
      { kr: '달다', pr: 'Dal-da', vn: 'Ngọt' },
      { kr: '짜다', pr: 'Jja-da', vn: 'Mặn' },
      { kr: '쓰다', pr: 'Sseu-da', vn: 'Đắng' },
      { kr: '시다', pr: 'Si-da', vn: 'Chua' },
      { kr: '싱겁다', pr: 'Sing-geop-da', vn: 'Nhạt' },
      { kr: '뜨겁다', pr: 'Tteu-geop-da', vn: 'Nóng (Nhiệt độ)' },
      { kr: '차갑다', pr: 'Cha-gap-da', vn: 'Lạnh (Nhiệt độ)' },
      { kr: '따뜻하다', pr: 'Tta-tteut-ha-da', vn: 'Ấm áp' },
      { kr: '시원하다', pr: 'Si-won-ha-da', vn: 'Mát mẻ' },
      { kr: '채소', pr: 'Chae-so', vn: 'Rau củ' },
      { kr: '야채', pr: 'Ya-chae', vn: 'Rau xanh' },
      { kr: '생선', pr: 'Saeng-seon', vn: 'Cá' },
      { kr: '계란', pr: 'Gye-ran', vn: 'Trứng' },
      { kr: '소고기', pr: 'So-go-gi', vn: 'Thịt bò' },
      { kr: '돼지고기', pr: 'Dwae-ji-go-gi', vn: 'Thịt lợn' },
      { kr: '닭고기', pr: 'Dak-go-gi', vn: 'Thịt gà' },
      { kr: '김치', pr: 'Gim-chi', vn: 'Kim chi' },
      { kr: '라면', pr: 'Ra-myeon', vn: 'Mì tôm' },
      { kr: '국수', pr: 'Guk-su', vn: 'Mì sợi' },
      { kr: '찌개', pr: 'Jji-gae', vn: 'Canh hầm' },
      { kr: '국', pr: 'Guk', vn: 'Canh' },
      { kr: '반찬', pr: 'Ban-chan', vn: 'Món ăn kèm' },
      { kr: '소금', pr: 'So-geum', vn: 'Muối' },
      { kr: '설탕', pr: 'Seol-tang', vn: 'Đường' },
      { kr: '간장', pr: 'Gan-jang', vn: 'Xì dầu' },
      { kr: '고추장', pr: 'Go-chu-jang', vn: 'Tương ớt' },
      { kr: '참기름', pr: 'Cham-gi-reum', vn: 'Dầu mè' },
      { kr: '사과', pr: 'Sa-gwa', vn: 'Quả táo' },
      { kr: '바나나', pr: 'Ba-na-na', vn: 'Quả chuối' },
      { kr: '포도', pr: 'Po-do', vn: 'Quả nho' },
      { kr: '딸기', pr: 'Ttal-gi', vn: 'Quả dâu tây' },
      { kr: '수박', pr: 'Su-bak', vn: 'Quả dưa hấu' },
      { kr: '오렌지', pr: 'O-ren-ji', vn: 'Quả cam' },
      { kr: '귤', pr: 'Gyul', vn: 'Quả quýt' },
      { kr: '주스', pr: 'Ju-seu', vn: 'Nước ép' },
      { kr: '커피', pr: 'Keo-pi', vn: 'Cà phê' },
      { kr: '차', pr: 'Cha', vn: 'Trà' },
      { kr: '콜라', pr: 'Kol-ra', vn: 'Coca cola' },
      { kr: '사이다', pr: 'Sa-이-da', vn: 'Nước Sprite' },
      { kr: '맥주', pr: 'Maek-ju', vn: 'Bia' },
      { kr: '소주', pr: 'So-ju', vn: 'Rượu Soju' },
    ],
  },
  {
    id: 5,
    title: '5) 상태와 형용사\n(Trạng thái & Tính từ)',
    icon: '⭐',
    words: [
      { kr: '좋다', pr: 'Jot-da', vn: 'Tốt / Thích' },
      { kr: '나쁘다', pr: 'Na-ppeu-da', vn: 'Xấu' },
      { kr: '크다', pr: 'Keu-da', vn: 'To / Lớn' },
      { kr: '작다', pr: 'Jak-da', vn: 'Nhỏ' },
      { kr: '많다', pr: 'Man-ta', vn: 'Nhiều' },
      { kr: '적다', pr: 'Jeok-da', vn: 'Ít' },
      { kr: '비싸다', pr: 'Bi-ssa-da', vn: 'Đắt' },
      { kr: '싸다', pr: 'Ssa-da', vn: 'Rẻ' },
      { kr: '어렵다', pr: 'Eo-ryeop-da', vn: 'Khó' },
      { kr: '쉽다', pr: 'Swip-da', vn: 'Dễ' },
      { kr: '길다', pr: 'Gil-da', vn: 'Dài' },
      { kr: '짧다', pr: 'Jjal-da', vn: 'Ngắn' },
      { kr: '높다', pr: 'Nop-da', vn: 'Cao' },
      { kr: '낮다', pr: 'Nat-da', vn: 'Thấp' },
      { kr: '넓다', pr: 'Neol-da', vn: 'Rộng' },
      { kr: '좁다', pr: 'Jop-da', vn: 'Hẹp' },
      { kr: '멀다', pr: 'Meol-da', vn: 'Xa' },
      { kr: '가깝다', pr: 'Ga-kkap-da', vn: 'Gần' },
      { kr: '무겁다', pr: 'Mu-geop-da', vn: 'Nặng' },
      { kr: '가볍다', pr: 'Ga-byeop-da', vn: 'Nhẹ' },
      { kr: '빠르다', pr: 'Ppa-reu-da', vn: 'Nhanh' },
      { kr: '느리다', pr: 'Neu-ri-da', vn: 'Chậm' },
      { kr: '바쁘다', pr: 'Ba-ppeu-da', vn: 'Bận rộn' },
      { kr: '한가하다', pr: 'Han-ga-ha-da', vn: 'Rảnh rỗi' },
      { kr: '예쁘다', pr: 'Ye-ppeu-da', vn: 'Xinh đẹp' },
      { kr: '멋있다', pr: 'Meo-sit-da', vn: 'Đẹp trai' },
      { kr: '귀엽다', pr: 'Gwi-yeop-da', vn: 'Dễ thương' },
      { kr: '덥다', pr: 'Deop-da', vn: 'Nóng (Thời tiết)' },
      { kr: '춥다', pr: 'Chup-da', vn: 'Lạnh (Thời tiết)' },
      { kr: '재미있다', pr: 'Jae-mi-it-da', vn: 'Thú vị' },
      { kr: '재미없다', pr: 'Jae-mi-eop-da', vn: 'Nhàm chán' },
      { kr: '심심하다', pr: 'Sim-sim-ha-da', vn: 'Buồn tẻ' },
      { kr: '피곤하다', pr: 'Pi-gon-ha-da', vn: 'Mệt mỏi' },
      { kr: '아프다', pr: 'A-peu-da', vn: 'Đau / Ốm' },
      { kr: '건강하다', pr: 'Geon-gang-ha-da', vn: 'Khỏe mạnh' },
      { kr: '기쁘다', pr: 'Gi-ppeu-da', vn: 'Vui vẻ' },
      { kr: '슬프다', pr: 'Seul-peu-da', vn: 'Buồn bã' },
      { kr: '화나다', pr: 'Hwa-na-da', vn: 'Tức giận' },
      { kr: '무섭다', pr: 'Mu-seop-da', vn: 'Đáng sợ' },
      { kr: '이상하다', pr: 'I-sang-ha-da', vn: 'Kỳ lạ' },
      { kr: '깨끗하다', pr: 'Kkae-kkeut-ha-da', vn: 'Sạch sẽ' },
      { kr: '더럽다', pr: 'Deo-reop-da', vn: 'Bẩn thỉu' },
      { kr: '조용하다', pr: 'Jo-yong-ha-da', vn: 'Yên tĩnh' },
      { kr: '시끄럽다', pr: 'Si-kkeu-reop-da', vn: 'Ồn ào' },
      { kr: '밝다', pr: 'Bak-da', vn: 'Sáng sủa' },
      { kr: '어둡다', pr: 'Eo-dup-da', vn: 'Tối tăm' },
      { kr: '똑똑하다', pr: 'Ttok-ttok-ha-da', vn: 'Thông minh' },
      { kr: '친절하다', pr: 'Chin-jeol-ha-da', vn: 'Thân thiện' },
      { kr: '필요하다', pr: 'Pil-yo-ha-da', vn: 'Cần thiết' },
      { kr: '중요하다', pr: 'Jung-yo-ha-da', vn: 'Quan trọng' },
    ],
  },
  {
    id: 6,
    title: '6) 가족과 사람\n(Gia đình & Con người)',
    icon: '👨‍👩‍👧‍👦',
    words: [
      { kr: '가족', pr: 'Ga-jok', vn: 'Gia đình' },
      { kr: '부모님', pr: 'Bu-mo-nim', vn: 'Bố mẹ' },
      { kr: '아버지', pr: 'A-beo-ji', vn: 'Bố' },
      { kr: '어머니', pr: 'Eo-meo-ni', vn: 'Mẹ' },
      { kr: '아빠', pr: 'A-ppa', vn: 'Ba' },
      { kr: '엄마', pr: 'Eom-ma', vn: 'Má' },
      { kr: '할아버지', pr: 'Hal-a-beo-ji', vn: 'Ông' },
      { kr: '할머니', pr: 'Hal-meo-ni', vn: 'Bà' },
      { kr: '형', pr: 'Hyeong', vn: 'Anh (Nam gọi)' },
      { kr: '오빠', pr: 'O-ppa', vn: 'Anh (Nữ gọi)' },
      { kr: '누나', pr: 'Nu-na', vn: 'Chị (Nam gọi)' },
      { kr: '언니', pr: 'Eon-ni', vn: 'Chị (Nữ gọi)' },
      { kr: '동생', pr: 'Dong-saeng', vn: 'Em' },
      { kr: '남동생', pr: 'Nam-dong-saeng', vn: 'Em trai' },
      { kr: '여동생', pr: 'Yeo-dong-saeng', vn: 'Em gái' },
      { kr: '부부', pr: 'Bu-bu', vn: 'Vợ chồng' },
      { kr: '남편', pr: 'Nam-pyeon', vn: 'Chồng' },
      { kr: '아내', pr: 'A-nae', vn: 'Vợ' },
      { kr: '아들', pr: 'A-deul', vn: 'Con trai' },
      { kr: '딸', pr: 'Ttal', vn: 'Con gái' },
      { kr: '삼촌', pr: 'Sam-chon', vn: 'Chú / Cậu' },
      { kr: '이모', pr: 'I-mo', vn: 'Dì' },
      { kr: '고모', pr: 'Go-mo', vn: 'Cô' },
      { kr: '조카', pr: 'Jo-ka', vn: 'Cháu' },
      { kr: '사람', pr: 'Sa-ram', vn: 'Người' },
      { kr: '친구', pr: 'Chin-gu', vn: 'Bạn bè' },
      { kr: '남자', pr: 'Nam-ja', vn: 'Đàn ông' },
      { kr: '여자', pr: 'Yeo-ja', vn: 'Phụ nữ' },
      { kr: '아이', pr: 'A-i', vn: 'Đứa trẻ' },
      { kr: '어른', pr: 'Eo-reun', vn: 'Người lớn' },
      { kr: '아기', pr: 'A-gi', vn: 'Em bé' },
      { kr: '학생', pr: 'Hak-saeng', vn: 'Học sinh' },
      { kr: '선생님', pr: 'Seon-saeng-nim', vn: 'Giáo viên' },
      { kr: '의사', pr: 'Ui-sa', vn: 'Bác sĩ' },
      { kr: '간호사', pr: 'Gan-ho-sa', vn: 'Y tá' },
      { kr: '경찰', pr: 'Gyeong-chal', vn: 'Cảnh sát' },
      { kr: '소방관', pr: 'So-bang-gwan', vn: 'Lính cứu hỏa' },
      { kr: '요리사', pr: 'Yo-ri-sa', vn: 'Đầu bếp' },
      { kr: '기사', pr: 'Gi-sa', vn: 'Tài xế' },
      { kr: '회사원', pr: 'Hoe-sa-won', vn: 'Nhân viên công ty' },
      { kr: '은행원', pr: 'Eun-haeng-won', vn: 'Nhân viên ngân hàng' },
      { kr: '공무원', pr: 'Gong-mu-won', vn: 'Công chức' },
      { kr: '가수', pr: 'Ga-su', vn: 'Ca sĩ' },
      { kr: '배우', pr: 'Bae-u', vn: 'Diễn viên' },
      { kr: '직업', pr: 'Jik-eop', vn: 'Nghề nghiệp' },
      { kr: '이름', pr: 'I-reum', vn: 'Tên' },
      { kr: '나이', pr: 'Na-i', vn: 'Tuổi' },
      { kr: '살', pr: 'Sal', vn: 'Tuổi (đơn vị)' },
      { kr: '명', pr: 'Myeong', vn: 'Người (đơn vị)' },
      { kr: '분', pr: 'Bun', vn: 'Vị / Người (Kính ngữ)' },
    ],
  },
  {
    id: 7,
    title: '7) 쇼핑과 물건\n(Mua sắm & Đồ vật)',
    icon: '🛍️',
    words: [
      { kr: '쇼핑', pr: 'Syo-ping', vn: 'Mua sắm' },
      { kr: '물건', pr: 'Mul-geon', vn: 'Hàng hóa' },
      { kr: '돈', pr: 'Don', vn: 'Tiền' },
      { kr: '현금', pr: 'Hyeon-geum', vn: 'Tiền mặt' },
      { kr: '카드', pr: 'Ka-deu', vn: 'Thẻ' },
      { kr: '지갑', pr: 'Ji-gap', vn: 'Cái ví' },
      { kr: '영수증', pr: 'Yeong-su-jeung', vn: 'Hóa đơn' },
      { kr: '가격', pr: 'Ga-gyeok', vn: 'Giá cả' },
      { kr: '거스름돈', pr: 'Geo-seu-reum-don', vn: 'Tiền thừa' },
      { kr: '옷', pr: 'Ot', vn: 'Quần áo' },
      { kr: '바지', pr: 'Ba-ji', vn: 'Quần' },
      { kr: '치마', pr: 'Chi-ma', vn: 'Váy' },
      { kr: '티셔츠', pr: 'Ti-syeo-cheu', vn: 'Áo thun' },
      { kr: '코트', pr: 'Ko-teu', vn: 'Áo khoác' },
      { kr: '모자', pr: 'Mo-ja', vn: 'Mũ / Nón' },
      { kr: '안경', pr: 'An-gyeong', vn: 'Kính mắt' },
      { kr: '구두', pr: 'Gu-du', vn: 'Giày da' },
      { kr: '운동화', pr: 'Un-dong-hwa', vn: 'Giày thể thao' },
      { kr: '양말', pr: 'Yang-mal', vn: 'Tất / Vớ' },
      { kr: '가방', pr: 'Ga-bang', vn: 'Túi xách / Balo' },
      { kr: '시계', pr: 'Si-gye', vn: 'Đồng hồ' },
      { kr: '우산', pr: 'U-san', vn: 'Cái ô / Dù' },
      { kr: '핸드폰', pr: 'Haen-deu-pon', vn: 'Điện thoại' },
      { kr: '컴퓨터', pr: 'Keom-pyu-teo', vn: 'Máy tính' },
      { kr: '텔레비전', pr: 'Tel-re-bi-jeon', vn: 'Tivi' },
      { kr: '냉장고', pr: 'Naeng-jang-go', vn: 'Tủ lạnh' },
      { kr: '에어컨', pr: 'E-eo-keon', vn: 'Máy lạnh' },
      { kr: '책', pr: 'Chaek', vn: 'Sách' },
      { kr: '공책', pr: 'Gong-chaek', vn: 'Vở' },
      { kr: '펜', pr: 'Pen', vn: 'Bút' },
      { kr: '연필', pr: 'Yeon-pil', vn: 'Bút chì' },
      { kr: '지우개', pr: 'Ji-u-gae', vn: 'Cục tẩy' },
      { kr: '책상', pr: 'Chaek-sang', vn: 'Bàn học' },
      { kr: '의자', pr: 'Ui-ja', vn: 'Cái ghế' },
      { kr: '침대', pr: 'Chim-dae', vn: 'Giường' },
      { kr: '휴지', pr: 'Hyu-ji', vn: 'Giấy vệ sinh' },
      { kr: '수건', pr: 'Su-geon', vn: 'Khăn tắm' },
      { kr: '비누', pr: 'Bi-nu', vn: 'Xà phòng' },
      { kr: '칫솔', pr: 'Chit-sol', vn: 'Bàn chải răng' },
      { kr: '치약', pr: 'Chi-yak', vn: 'Kem đánh răng' },
      { kr: '샴푸', pr: 'Syam-pu', vn: 'Dầu gội' },
      { kr: '컵', pr: 'Keop', vn: 'Cốc / Ly' },
      { kr: '그릇', pr: 'Geu-reut', vn: 'Bát / Chén' },
      { kr: '숟가락', pr: 'Sut-ga-rak', vn: 'Thìa' },
      { kr: '젓가락', pr: 'Jeot-ga-rak', vn: 'Đũa' },
      { kr: '가위', pr: 'Ga-wi', vn: 'Cái kéo' },
      { kr: '칼', pr: 'Kal', vn: 'Con dao' },
      { kr: '쓰레기통', pr: 'Sseu-re-gi-tong', vn: 'Thùng rác' },
      { kr: '봉투', pr: 'Bong-tu', vn: 'Túi / Phong bì' },
      { kr: '선물', pr: 'Seon-mul', vn: 'Quà tặng' },
    ],
  },
  {
    id: 8,
    title: '8) 교통과 여행\n(Giao thông & Du lịch)',
    icon: '✈️',
    words: [
      { kr: '교통', pr: 'Gyo-tong', vn: 'Giao thông' },
      { kr: '여행', pr: 'Yeo-haeng', vn: 'Du lịch' },
      { kr: '휴가', pr: 'Hyu-ga', vn: 'Kỳ nghỉ' },
      { kr: '여권', pr: 'Yeo-gwon', vn: 'Hộ chiếu' },
      { kr: '비자', pr: 'Bi-ja', vn: 'Visa' },
      { kr: '비행기', pr: 'Bi-haeng-gi', vn: 'Máy bay' },
      { kr: '기차', pr: 'Gi-cha', vn: 'Tàu hỏa' },
      { kr: '지하철', pr: 'Ji-ha-cheol', vn: 'Tàu điện ngầm' },
      { kr: '버스', pr: 'Beo-seu', vn: 'Xe buýt' },
      { kr: '택시', pr: 'Taek-si', vn: 'Taxi' },
      { kr: '자전거', pr: 'Ja-jeon-geo', vn: 'Xe đạp' },
      { kr: '오토바이', pr: 'O-to-ba-i', vn: 'Xe máy' },
      { kr: '자동차', pr: 'Ja-dong-cha', vn: 'Ô tô' },
      { kr: '배', pr: 'Bae', vn: 'Tàu / Thuyền' },
      { kr: '역', pr: 'Yeok', vn: 'Ga tàu' },
      { kr: '정류장', pr: 'Jeong-ryu-jang', vn: 'Trạm dừng' },
      { kr: '공항', pr: 'Gong-hang', vn: 'Sân bay' },
      { kr: '터미널', pr: 'Teo-mi-neol', vn: 'Bến xe' },
      { kr: '항구', pr: 'Hang-gu', vn: 'Bến cảng' },
      { kr: '표', pr: 'Pyo', vn: 'Vé' },
      { kr: '티켓', pr: 'Ti-ket', vn: 'Vé (Ticket)' },
      { kr: '요금', pr: 'Yo-geum', vn: 'Tiền cước / Phí' },
      { kr: '교통카드', pr: 'Gyo-tong-ka-deu', vn: 'Thẻ giao thông' },
      { kr: '환승', pr: 'Hwan-seung', vn: 'Chuyển tuyến' },
      { kr: '출발', pr: 'Chul-bal', vn: 'Xuất phát' },
      { kr: '도착', pr: 'Do-chak', vn: 'Đến nơi' },
      { kr: '타다', pr: 'Ta-da', vn: 'Lên xe' },
      { kr: '내리다', pr: 'Nae-ri-da', vn: 'Xuống xe' },
      { kr: '갈아타다', pr: 'Gal-a-ta-da', vn: 'Đổi xe' },
      { kr: '운전하다', pr: 'Un-jeon-ha-da', vn: 'Lái xe' },
      { kr: '걷다', pr: 'Geot-da', vn: 'Đi bộ' },
      { kr: '길', pr: 'Gil', vn: 'Con đường' },
      { kr: '거리', pr: 'Geo-ri', vn: 'Phố xá' },
      { kr: '신호등', pr: 'Sin-ho-deung', vn: 'Đèn giao thông' },
      { kr: '횡단보도', pr: 'Hoeng-dan-bo-do', vn: 'Vạch qua đường' },
      { kr: '다리', pr: 'Da-ri', vn: 'Cây cầu' },
      { kr: '지도', pr: 'Ji-do', vn: 'Bản đồ' },
      { kr: '사진', pr: 'Sa-jin', vn: 'Bức ảnh' },
      { kr: '카메라', pr: 'Ka-me-ra', vn: 'Máy ảnh' },
      { kr: '추억', pr: 'Chu-eok', vn: 'Kỷ niệm' },
      { kr: '호텔', pr: 'Ho-tel', vn: 'Khách sạn' },
      { kr: '숙소', pr: 'Suk-so', vn: 'Chỗ ở' },
      { kr: '예약', pr: 'Ye-yak', vn: 'Đặt trước' },
      { kr: '안내', pr: 'An-nae', vn: 'Hướng dẫn' },
      { kr: '관광', pr: 'Gwan-gwang', vn: 'Tham quan' },
      { kr: '외국', pr: 'Oe-guk', vn: 'Nước ngoài' },
      { kr: '외국인', pr: 'Oe-guk-in', vn: 'Người nước ngoài' },
      { kr: '고향', pr: 'Go-hyang', vn: 'Quê hương' },
      { kr: '짐', pr: 'Jim', vn: 'Hành lý' },
      { kr: '가이드', pr: 'Ga-i-deu', vn: 'Hướng dẫn viên' },
    ],
  },
  {
    id: 9,
    title: '9) 취미와 일상\n(Sở thích & Đời sống)',
    icon: '🎮',
    words: [
      { kr: '취미', pr: 'Chwi-mi', vn: 'Sở thích' },
      { kr: '여가', pr: 'Yeo-ga', vn: 'Thời gian rảnh' },
      { kr: '영화', pr: 'Yeong-hwa', vn: 'Phim ảnh' },
      { kr: '음악', pr: 'Eum-ak', vn: 'Âm nhạc' },
      { kr: '노래', pr: 'No-rae', vn: 'Bài hát' },
      { kr: '춤', pr: 'Chum', vn: 'Nhảy múa' },
      { kr: '독서', pr: 'Dok-seo', vn: 'Đọc sách' },
      { kr: '운동', pr: 'Un-dong', vn: 'Vận động' },
      { kr: '축구', pr: 'Chuk-gu', vn: 'Bóng đá' },
      { kr: '농구', pr: 'Nong-gu', vn: 'Bóng rổ' },
      { kr: '야구', pr: 'Ya-gu', vn: 'Bóng chày' },
      { kr: '수영', pr: 'Su-yeong', vn: 'Bơi lội' },
      { kr: '등산', pr: 'Deung-san', vn: 'Leo núi' },
      { kr: '산책', pr: 'San-chaek', vn: 'Đi dạo' },
      { kr: '낚시', pr: 'Nak-si', vn: 'Câu cá' },
      { kr: '게임', pr: 'Ge-im', vn: 'Trò chơi' },
      { kr: '피아노', pr: 'Pi-a-no', vn: 'Đàn piano' },
      { kr: '기타', pr: 'Gi-ta', vn: 'Đàn guitar' },
      { kr: '그림', pr: 'Geu-rim', vn: 'Bức tranh' },
      { kr: '요리', pr: 'Yo-ri', vn: 'Nấu ăn' },
      { kr: '청소', pr: 'Cheong-so', vn: 'Dọn dẹp' },
      { kr: '빨래', pr: 'Ppal-rae', vn: 'Giặt giũ' },
      { kr: '설거지', pr: 'Seol-geo-ji', vn: 'Rửa bát' },
      { kr: '목욕', pr: 'Mok-yok', vn: 'Tắm bồn' },
      { kr: '샤워', pr: 'Sya-wo', vn: 'Tắm vòi sen' },
      { kr: '인터넷', pr: 'In-teo-net', vn: 'Internet' },
      { kr: '드라마', pr: 'Deu-ra-ma', vn: 'Phim truyền hình' },
      { kr: '예능', pr: 'Ye-neung', vn: 'Chương trình giải trí' },
      { kr: '뉴스', pr: 'Nyu-seu', vn: 'Tin tức' },
      { kr: '전화', pr: 'Jeon-hwa', vn: 'Điện thoại' },
      { kr: '문자', pr: 'Mun-ja', vn: 'Tin nhắn' },
      { kr: '모임', pr: 'Mo-im', vn: 'Buổi tụ tập' },
      { kr: '회식', pr: 'Hoe-sik', vn: 'Tiệc công ty' },
      { kr: '파티', pr: 'Pa-ti', vn: 'Bữa tiệc' },
      { kr: '생일', pr: 'Saeng-il', vn: 'Sinh nhật' },
      { kr: '축하', pr: 'Chuk-ha', vn: 'Chúc mừng' },
      { kr: '편지', pr: 'Pyeon-ji', vn: 'Bức thư' },
      { kr: '일기', pr: 'Il-gi', vn: 'Nhật ký' },
      { kr: '꿈', pr: 'Kkum', vn: 'Giấc mơ' },
      { kr: '계획', pr: 'Gye-hoek', vn: 'Kế hoạch' },
      { kr: '휴식', pr: 'Hyu-sik', vn: 'Sự nghỉ ngơi' },
      { kr: '낮잠', pr: 'Nat-jam', vn: 'Ngủ trưa' },
      { kr: '일상', pr: 'Il-sang', vn: 'Đời sống thường ngày' },
      { kr: '생활', pr: 'Saeng-hwal', vn: 'Sinh hoạt' },
      { kr: '일어나다', pr: 'Il-eo-na-da', vn: 'Thức dậy' },
      { kr: '세수하다', pr: 'Se-su-ha-da', vn: 'Rửa mặt' },
      { kr: '화장하다', pr: 'Hwa-jang-ha-da', vn: 'Trang điểm' },
      { kr: '준비하다', pr: 'Jun-bi-ha-da', vn: 'Chuẩn bị' },
      { kr: '출근하다', pr: 'Chul-geun-ha-da', vn: 'Đi làm' },
      { kr: '퇴근하다', pr: 'Toe-geun-ha-da', vn: 'Tan làm' },
    ],
  },
  {
    id: 10,
    title: '10) 마법 단어 1 - 발음 유사\n(Từ Hán-Hàn giống nhau)',
    icon: '🔮',
    words: [
      { kr: '주의', pr: 'Ju-ui', vn: 'Chú ý' },
      { kr: '준비', pr: 'Jun-bi', vn: 'Chuẩn bị' },
      { kr: '동의', pr: 'Dong-ui', vn: 'Đồng ý' },
      { kr: '대학', pr: 'Dae-hak', vn: 'Đại học' },
      { kr: '국가', pr: 'Guk-ga', vn: 'Quốc gia' },
      { kr: '국제', pr: 'Guk-je', vn: 'Quốc tế' },
      { kr: '세계', pr: 'Se-gye', vn: 'Thế giới' },
      { kr: '시민', pr: 'Si-min', vn: 'Thị dân / Công dân' },
      { kr: '인구', pr: 'In-gu', vn: 'Nhân khẩu / Dân số' },
      { kr: '독립', pr: 'Dok-rip', vn: 'Độc lập' },
      { kr: '평화', pr: 'Pyeong-hwa', vn: 'Bình hòa / Hòa bình' },
      { kr: '무료', pr: 'Mu-ryo', vn: 'Miễn phí' },
      { kr: '공기', pr: 'Gong-gi', vn: 'Không khí' },
      { kr: '관리', pr: 'Gwan-ri', vn: 'Quản lý' },
      { kr: '가수', pr: 'Ga-su', vn: 'Ca sĩ' },
      { kr: '도구', pr: 'Do-gu', vn: 'Đạo cụ' },
      { kr: '태도', pr: 'Tae-do', vn: 'Thái độ' },
      { kr: '다수', pr: 'Da-su', vn: 'Đa số' },
      { kr: '소수', pr: 'So-su', vn: 'Thiểu số' },
      { kr: '과학', pr: 'Gwa-hak', vn: 'Khoa học' },
      { kr: '수학', pr: 'Su-hak', vn: 'Số học / Toán' },
      { kr: '역사', pr: 'Yeok-sa', vn: 'Lịch sử' },
      { kr: '유학', pr: 'Yu-hak', vn: 'Du học' },
      { kr: '감동', pr: 'Gam-dong', vn: 'Cảm động' },
      { kr: '낙관', pr: 'Nak-gwan', vn: 'Lạc quan' },
      { kr: '비관', pr: 'Bi-gwan', vn: 'Bi quan' },
      { kr: '행복', pr: 'Haeng-bok', vn: 'Hạnh phúc' },
      { kr: '신중', pr: 'Sin-jung', vn: 'Thận trọng' },
      { kr: '단순', pr: 'Dan-sun', vn: 'Đơn thuần' },
      { kr: '솔직', pr: 'Sol-jik', vn: 'Suất trực / Thẳng thắn' },
      { kr: '안심', pr: 'An-sim', vn: 'An tâm' },
      { kr: '후회', pr: 'Hu-hoe', vn: 'Hậu hối / Hối hận' },
      { kr: '기억', pr: 'Gi-eok', vn: 'Ký ức' },
      { kr: '기록', pr: 'Gi-rok', vn: 'Ký lục / Ghi chép' },
      { kr: '기적', pr: 'Gi-jeok', vn: 'Kỳ tích' },
      { kr: '기본', pr: 'Gi-bon', vn: 'Cơ bản' },
      { kr: '기초', pr: 'Gi-cho', vn: 'Cơ sở / Nền tảng' },
      { kr: '기회', pr: 'Gi-hoe', vn: 'Cơ hội' },
      { kr: '노력', pr: 'No-ryeok', vn: 'Nỗ lực' },
      { kr: '능력', pr: 'Neung-ryeok', vn: 'Năng lực' },
      { kr: '대화', pr: 'Dae-hwa', vn: 'Đối thoại' },
      { kr: '도착', pr: 'Do-chak', vn: 'Đáo trước / Đến nơi' },
      { kr: '매력', pr: 'Mae-ryeok', vn: 'Mị lực / Sức hút' },
      { kr: '목적', pr: 'Mok-jeok', vn: 'Mục đích' },
      { kr: '발전', pr: 'Bal-jeon', vn: 'Phát triển' },
      { kr: '발견', pr: 'Bal-gyeon', vn: 'Phát hiện' },
      { kr: '발음', pr: 'Bal-eum', vn: 'Phát âm' },
      { kr: '방법', pr: 'Bang-beop', vn: 'Phương pháp' },
      { kr: '방향', pr: 'Bang-hyang', vn: 'Phương hướng' },
      { kr: '변화', pr: 'Byeon-hwa', vn: 'Biến hóa / Thay đổi' },
    ],
  },
  {
    id: 11,
    title: '11) 신체와 건강\n(Cơ thể & Sức khỏe)',
    icon: '🏥',
    words: [
      { kr: '머리', pr: 'Meo-ri', vn: 'Đầu / Tóc' },
      { kr: '눈', pr: 'Nun', vn: 'Mắt' },
      { kr: '코', pr: 'Ko', vn: 'Mũi' },
      { kr: '입', pr: 'Ip', vn: 'Miệng' },
      { kr: '귀', pr: 'Gwi', vn: 'Tai' },
      { kr: '얼굴', pr: 'Eol-gul', vn: 'Khuôn mặt' },
      { kr: '목', pr: 'Mok', vn: 'Cổ' },
      { kr: '어깨', pr: 'Eo-kkae', vn: 'Vai' },
      { kr: '팔', pr: 'Pal', vn: 'Cánh tay' },
      { kr: '손', pr: 'Son', vn: 'Bàn tay' },
      { kr: '손가락', pr: 'Son-ga-rak', vn: 'Ngón tay' },
      { kr: '가슴', pr: 'Ga-seum', vn: 'Ngực' },
      { kr: '배', pr: 'Bae', vn: 'Bụng' },
      { kr: '등', pr: 'Deung', vn: 'Lưng' },
      { kr: '허리', pr: 'Heo-ri', vn: 'Eo' },
      { kr: '다리', pr: 'Da-ri', vn: 'Chân' },
      { kr: '무릎', pr: 'Mu-reup', vn: 'Đầu gối' },
      { kr: '발', pr: 'Bal', vn: 'Bàn chân' },
      { kr: '발가락', pr: 'Bal-ga-rak', vn: 'Ngón chân' },
      { kr: '피부', pr: 'Pi-bu', vn: 'Da' },
      { kr: '뼈', pr: 'Ppyeo', vn: 'Xương' },
      { kr: '피', pr: 'Pi', vn: 'Máu' },
      { kr: '병원', pr: 'Byeong-won', vn: 'Bệnh viện' },
      { kr: '의사', pr: 'Ui-sa', vn: 'Bác sĩ' },
      { kr: '간호사', pr: 'Gan-ho-sa', vn: 'Y tá' },
      { kr: '환자', pr: 'Hwan-ja', vn: 'Bệnh nhân' },
      { kr: '약', pr: 'Yak', vn: 'Thuốc' },
      { kr: '약국', pr: 'Yak-guk', vn: 'Hiệu thuốc' },
      { kr: '주사', pr: 'Ju-sa', vn: 'Mũi tiêm' },
      { kr: '수술', pr: 'Su-sul', vn: 'Phẫu thuật' },
      { kr: '감기', pr: 'Gam-gi', vn: 'Cảm cúm' },
      { kr: '기침', pr: 'Gi-chim', vn: 'Ho' },
      { kr: '콧물', pr: 'Kot-mul', vn: 'Nước mũi' },
      { kr: '열', pr: 'Yeol', vn: 'Sốt' },
      { kr: '두통', pr: 'Du-tong', vn: 'Đau đầu' },
      { kr: '치통', pr: 'Chi-tong', vn: 'Đau răng' },
      { kr: '복통', pr: 'Bok-tong', vn: 'Đau bụng' },
      { kr: '소화제', pr: 'So-hwa-je', vn: 'Thuốc tiêu hóa' },
      { kr: '진통제', pr: 'Jin-tong-je', vn: 'Thuốc giảm đau' },
      { kr: '해열제', pr: 'Hae-yeol-je', vn: 'Thuốc hạ sốt' },
      { kr: '처방전', pr: 'Cheo-bang-jeon', vn: 'Đơn thuốc' },
      { kr: '입원', pr: 'Ip-won', vn: 'Nhập viện' },
      { kr: '퇴원', pr: 'Toe-won', vn: 'Xuất viện' },
      { kr: '건강', pr: 'Geon-gang', vn: 'Sức khỏe' },
      { kr: '다치다', pr: 'Da-chi-da', vn: 'Bị thương' },
      { kr: '낫다', pr: 'Nat-da', vn: 'Khỏi bệnh' },
      { kr: '아프다', pr: 'A-peu-da', vn: 'Đau / Ốm' },
      { kr: '피곤하다', pr: 'Pi-gon-ha-da', vn: 'Mệt mỏi' },
      { kr: '쓰러지다', pr: 'Sseu-reo-ji-da', vn: 'Ngất xỉu' },
      { kr: '치료하다', pr: 'Chi-ryo-ha-da', vn: 'Điều trị' },
    ],
  },
  {
    id: 12,
    title: '12) 자연과 날씨\n(Thiên nhiên & Thời tiết)',
    icon: '🌦️',
    words: [
      { kr: '자연', pr: 'Ja-yeon', vn: 'Thiên nhiên' },
      { kr: '하늘', pr: 'Ha-neul', vn: 'Bầu trời' },
      { kr: '땅', pr: 'Ttang', vn: 'Đất' },
      { kr: '해', pr: 'Hae', vn: 'Mặt trời' },
      { kr: '달', pr: 'Dal', vn: 'Mặt trăng' },
      { kr: '별', pr: 'Byeol', vn: 'Ngôi sao' },
      { kr: '구름', pr: 'Gu-reum', vn: 'Đám mây' },
      { kr: '비', pr: 'Bi', vn: 'Mưa' },
      { kr: '눈', pr: 'Nun', vn: 'Tuyết' },
      { kr: '바람', pr: 'Ba-ram', vn: 'Gió' },
      { kr: '안개', pr: 'An-gae', vn: 'Sương mù' },
      { kr: '번개', pr: 'Beon-gae', vn: 'Tia chớp' },
      { kr: '천둥', pr: 'Cheon-dung', vn: 'Sấm' },
      { kr: '무지개', pr: 'Mu-ji-gae', vn: 'Cầu vồng' },
      { kr: '날씨', pr: 'Nal-ssi', vn: 'Thời tiết' },
      { kr: '맑다', pr: 'Mak-da', vn: 'Trong xanh' },
      { kr: '흐리다', pr: 'Heu-ri-da', vn: 'Âm u / Nhiều mây' },
      { kr: '따뜻하다', pr: 'Tta-tteut-ha-da', vn: 'Ấm áp' },
      { kr: '시원하다', pr: 'Si-won-ha-da', vn: 'Mát mẻ' },
      { kr: '덥다', pr: 'Deop-da', vn: 'Nóng' },
      { kr: '춥다', pr: 'Chup-da', vn: 'Lạnh' },
      { kr: '태풍', pr: 'Tae-pung', vn: 'Bão' },
      { kr: '홍수', pr: 'Hong-su', vn: 'Lũ lụt' },
      { kr: '지진', pr: 'Ji-jin', vn: 'Động đất' },
      { kr: '불', pr: 'Bul', vn: 'Lửa' },
      { kr: '물', pr: 'Mul', vn: 'Nước' },
      { kr: '나무', pr: 'Na-mu', vn: 'Cây' },
      { kr: '꽃', pr: 'Kkot', vn: 'Hoa' },
      { kr: '풀', pr: 'Pul', vn: 'Cỏ' },
      { kr: '잎', pr: 'Ip', vn: 'Lá cây' },
      { kr: '산', pr: 'San', vn: 'Núi' },
      { kr: '바다', pr: 'Ba-da', vn: 'Biển' },
      { kr: '강', pr: 'Gang', vn: 'Sông' },
      { kr: '호수', pr: 'Ho-su', vn: 'Hồ' },
      { kr: '섬', pr: 'Seom', vn: 'Đảo' },
      { kr: '동물', pr: 'Dong-mul', vn: 'Động vật' },
      { kr: '개', pr: 'Gae', vn: 'Con chó' },
      { kr: '고양이', pr: 'Go-yang-i', vn: 'Con mèo' },
      { kr: '새', pr: 'Sae', vn: 'Con chim' },
      { kr: '물고기', pr: 'Mul-go-gi', vn: 'Con cá' },
      { kr: '소', pr: 'So', vn: 'Con bò' },
      { kr: '돼지', pr: 'Dwae-ji', vn: 'Con lợn' },
      { kr: '닭', pr: 'Dak', vn: 'Con gà' },
      { kr: '호랑이', pr: 'Ho-rang-i', vn: 'Con hổ' },
      { kr: '사자', pr: 'Sa-ja', vn: 'Con sư tử' },
      { kr: '곰', pr: 'Gom', vn: 'Con gấu' },
      { kr: '토끼', pr: 'To-kki', vn: 'Con thỏ' },
      { kr: '원숭이', pr: 'Won-sung-i', vn: 'Con khỉ' },
      { kr: '쥐', pr: 'Jwi', vn: 'Con chuột' },
      { kr: '환경', pr: 'Hwan-gyeong', vn: 'Môi trường' },
    ],
  },
  {
    id: 13,
    title: '13) 직장과 업무\n(Văn phòng & Công việc)',
    icon: '🏢',
    words: [
      { kr: '직장', pr: 'Jik-jang', vn: 'Nơi làm việc' },
      { kr: '사무실', pr: 'Sa-mu-sil', vn: 'Văn phòng' },
      { kr: '책상', pr: 'Chaek-sang', vn: 'Bàn làm việc' },
      { kr: '컴퓨터', pr: 'Keom-pyu-teo', vn: 'Máy tính' },
      { kr: '복사기', pr: 'Bok-sa-gi', vn: 'Máy photocopy' },
      { kr: '프린터', pr: 'Peu-rin-teo', vn: 'Máy in' },
      { kr: '서류', pr: 'Seo-ryu', vn: 'Tài liệu' },
      { kr: '결재', pr: 'Gyeol-jae', vn: 'Phê duyệt' },
      { kr: '보고서', pr: 'Bo-go-seo', vn: 'Bản báo cáo' },
      { kr: '회의', pr: 'Hoe-ui', vn: 'Cuộc họp' },
      { kr: '출장', pr: 'Chul-jang', vn: 'Công tác' },
      { kr: '명함', pr: 'Myeong-ham', vn: 'Danh thiếp' },
      { kr: '이메일', pr: 'I-me-il', vn: 'Email' },
      { kr: '전화', pr: 'Jeon-hwa', vn: 'Điện thoại' },
      { kr: '팩스', pr: 'Paek-seu', vn: 'Máy fax' },
      { kr: '사장', pr: 'Sa-jang', vn: 'Giám đốc' },
      { kr: '부장', pr: 'Bu-jang', vn: 'Trưởng phòng' },
      { kr: '과장', pr: 'Gwa-jang', vn: 'Trưởng bộ phận' },
      { kr: '대리', pr: 'Dae-ri', vn: 'Phó phòng' },
      { kr: '사원', pr: 'Sa-won', vn: 'Nhân viên' },
      { kr: '동료', pr: 'Dong-ryo', vn: 'Đồng nghiệp' },
      { kr: '상사', pr: 'Sang-sa', vn: 'Cấp trên' },
      { kr: '부하', pr: 'Bu-ha', vn: 'Cấp dưới' },
      { kr: '회식', pr: 'Hoe-sik', vn: 'Tiệc công ty' },
      { kr: '월급', pr: 'Wol-geup', vn: 'Lương tháng' },
      { kr: '보너스', pr: 'Bo-neo-seu', vn: 'Tiền thưởng' },
      { kr: '승진', pr: 'Seung-jin', vn: 'Thăng chức' },
      { kr: '휴가', pr: 'Hyu-ga', vn: 'Nghỉ phép' },
      { kr: '연차', pr: 'Yeon-cha', vn: 'Nghỉ phép năm' },
      { kr: '반차', pr: 'Ban-cha', vn: 'Nghỉ nửa ngày' },
      { kr: '병가', pr: 'Byeong-ga', vn: 'Nghỉ ốm' },
      { kr: '지각', pr: 'Ji-gak', vn: 'Đi muộn' },
      { kr: '조퇴', pr: 'Jo-toe', vn: 'Về sớm' },
      { kr: '야근', pr: 'Ya-geun', vn: 'Làm thêm giờ' },
      { kr: '퇴근', pr: 'Toe-geun', vn: 'Tan làm' },
      { kr: '출근', pr: 'Chul-geun', vn: 'Đi làm' },
      { kr: '취직', pr: 'Chwi-jik', vn: 'Xin việc' },
      { kr: '퇴사', pr: 'Toe-sa', vn: 'Nghỉ việc' },
      { kr: '면접', pr: 'Myeon-jeop', vn: 'Phỏng vấn' },
      { kr: '이력서', pr: 'I-ryeok-seo', vn: 'Sơ yếu lý lịch' },
      { kr: '계약서', pr: 'Gye-yak-seo', vn: 'Bản hợp đồng' },
      { kr: '업무', pr: 'Eom-mu', vn: 'Công việc' },
      { kr: '업무량', pr: 'Eom-mu-ryang', vn: 'Khối lượng công việc' },
      { kr: '스트레스', pr: 'Seu-teu-re-seu', vn: 'Căng thẳng' },
      { kr: '성공', pr: 'Seong-gong', vn: 'Thành công' },
      { kr: '실패', pr: 'Sil-pae', vn: 'Thất bại' },
      { kr: '목표', pr: 'Mok-pyo', vn: 'Mục tiêu' },
      { kr: '프로젝트', pr: 'Peu-ro-jek-teu', vn: 'Dự án' },
      { kr: '아이디어', pr: 'A-이-디-어', vn: 'Ý tưởng' },
      { kr: '동의하다', pr: 'Dong-ui-ha-da', vn: 'Đồng ý' },
    ],
  },
  {
    id: 14,
    title: '14) K-Pop & K-Drama\n(Văn hóa Thần tượng)',
    icon: '🎤',
    words: [
      { kr: '노래', pr: 'No-rae', vn: 'Bài hát' },
      { kr: '춤', pr: 'Chum', vn: 'Điệu nhảy' },
      { kr: '가수', pr: 'Ga-su', vn: 'Ca sĩ' },
      { kr: '아이돌', pr: 'A-i-dol', vn: 'Thần tượng' },
      { kr: '팬', pr: 'Paen', vn: 'Người hâm mộ' },
      { kr: '팬클럽', pr: 'Paen-keul-leop', vn: 'Câu lạc bộ fan' },
      { kr: '콘서트', pr: 'Kon-seo-teu', vn: 'Buổi hòa nhạc' },
      { kr: '공연', pr: 'Gong-yeon', vn: 'Biểu diễn' },
      { kr: '무대', pr: 'Mu-dae', vn: 'Sân khấu' },
      { kr: '응원', pr: 'Eung-won', vn: 'Cổ vũ' },
      { kr: '응원봉', pr: 'Eung-won-bong', vn: 'Lightstick' },
      { kr: '앨범', pr: 'Ael-beom', vn: 'Album' },
      { kr: '발매', pr: 'Bal-mae', vn: 'Phát hành' },
      { kr: '뮤직비디오', pr: 'Myu-jik-bi-di-o', vn: 'Video âm nhạc' },
      { kr: '가사', pr: 'Ga-sa', vn: 'Lời bài hát' },
      { kr: '작곡', pr: 'Jak-gok', vn: 'Sáng tác nhạc' },
      { kr: '작사', pr: 'Jak-sa', vn: 'Viết lời' },
      { kr: '데뷔', pr: 'De-bwi', vn: 'Ra mắt' },
      { kr: '컴백', pr: 'Keom-baek', vn: 'Trở lại' },
      { kr: '1위', pr: 'Il-wi', vn: 'Hạng 1' },
      { kr: '시상식', pr: 'Si-sang-sik', vn: 'Lễ trao giải' },
      { kr: '기획사', pr: 'Gi-hoek-sa', vn: 'Công ty giải trí' },
      { kr: '연습생', pr: 'Yeon-seup-saeng', vn: 'Thực tập sinh' },
      { kr: '오디션', pr: 'O-di-syeon', vn: 'Thử giọng' },
      { kr: '매력', pr: 'Mae-ryeok', vn: 'Sức hấp dẫn' },
      { kr: '귀엽다', pr: 'Gwi-yeop-da', vn: 'Đáng yêu' },
      { kr: '잘생기다', pr: 'Jal-saeng-gi-da', vn: 'Đẹp trai' },
      { kr: '예쁘다', pr: 'Ye-ppeu-da', vn: 'Xinh đẹp' },
      { kr: '멋지다', pr: 'Meot-ji-da', vn: 'Tuyệt vời / Ngầu' },
      { kr: '사랑하다', pr: 'Sa-rang-ha-da', vn: 'Yêu' },
      { kr: '최애', pr: 'Choe-ae', vn: 'Thành viên yêu thích nhất' },
      { kr: '덕질', pr: 'Deok-jil', vn: 'Việc theo đuổi Idol' },
      { kr: '티켓팅', pr: 'Ti-ket-ting', vn: 'Săn vé' },
      { kr: '매진', pr: 'Mae-jin', vn: 'Bán hết' },
      { kr: '스트리밍', pr: 'Seu-teu-ri-ming', vn: 'Cày view' },
      { kr: '조회수', pr: 'Jo-hoe-su', vn: 'Lượt xem' },
      { kr: '구독', pr: 'Gu-dok', vn: 'Đăng ký' },
      { kr: '좋아요', pr: 'Jo-a-yo', vn: 'Thích' },
      { kr: '댓글', pr: 'Daet-geul', vn: 'Bình luận' },
      { kr: '라이브', pr: 'Ra-i-beu', vn: 'Phát trực tiếp' },
      { kr: '방송', pr: 'Bang-song', vn: 'Phát sóng' },
      { kr: '녹화', pr: 'Nok-hwa', vn: 'Ghi hình' },
      { kr: '대박', pr: 'Dae-bak', vn: 'Đỉnh / Xuất sắc' },
      { kr: '눈물', pr: 'Nun-mul', vn: 'Nước mắt' },
      { kr: '감동', pr: 'Gam-dong', vn: 'Cảm động' },
      { kr: '행복', pr: 'Haeng-bok', vn: 'Hạnh phúc' },
      { kr: '영원히', pr: 'Yeong-won-hi', vn: 'Mãi mãi' },
      { kr: '기억하다', pr: 'Gi-eok-ha-da', vn: 'Nhớ' },
      { kr: '함께', pr: 'Ham-kke', vn: 'Cùng nhau' },
      { kr: '약속', pr: 'Yak-sok', vn: 'Lời hứa' },
    ],
  },
  {
    id: 15,
    title: '15) 마법 단어 2 - 발음 유사\n(Từ Hán-Hàn giống nhau)',
    icon: '🌟',
    words: [
      { kr: '감동', pr: 'Gam-dong', vn: 'Cảm động' },
      { kr: '감사', pr: 'Gam-sa', vn: 'Cảm tạ / Cảm ơn' },
      { kr: '결과', pr: 'Gyeol-gwa', vn: 'Kết quả' },
      { kr: '결정', pr: 'Gyeol-jeong', vn: 'Quyết định' },
      { kr: '결혼', pr: 'Gyeol-hon', vn: 'Kết hôn' },
      { kr: '경고', pr: 'Gyeong-go', vn: 'Cảnh cáo' },
      { kr: '경험', pr: 'Gyeong-heom', vn: 'Kinh nghiệm' },
      { kr: '광고', pr: 'Gwang-go', vn: 'Quảng cáo' },
      { kr: '관심', pr: 'Gwan-sim', vn: 'Quan tâm' },
      { kr: '관리', pr: 'Gwan-ri', vn: 'Quản lý' },
      { kr: '구조', pr: 'Gu-jo', vn: 'Cứu trợ / Cấu tạo' },
      { kr: '권리', pr: 'Gwon-ri', vn: 'Quyền lợi' },
      { kr: '규칙', pr: 'Gyu-chik', vn: 'Quy tắc' },
      { kr: '기계', pr: 'Gi-gye', vn: 'Cơ giới / Máy móc' },
      { kr: '기념', pr: 'Gi-nyeom', vn: 'Kỷ niệm' },
      { kr: '대답', pr: 'Dae-dap', vn: 'Đối đáp / Trả lời' },
      { kr: '도로', pr: 'Do-ro', vn: 'Đạo lộ / Đường bộ' },
      { kr: '도시', pr: 'Do-si', vn: 'Đô thị' },
      { kr: '독서', pr: 'Dok-seo', vn: 'Độc thư / Đọc sách' },
      { kr: '동의', pr: 'Dong-ui', vn: 'Đồng ý' },
      { kr: '명령', pr: 'Myeong-ryeong', vn: 'Mệnh lệnh' },
      { kr: '모순', pr: 'Mo-sun', vn: 'Mâu thuẫn' },
      { kr: '무시', pr: 'Mu-si', vn: 'Vô thị / Phớt lờ' },
      { kr: '미술', pr: 'Mi-sul', vn: 'Mỹ thuật' },
      { kr: '발견', pr: 'Bal-gyeon', vn: 'Phát kiến / Phát hiện' },
      { kr: '발전', pr: 'Bal-jeon', vn: 'Phát triển' },
      { kr: '범죄', pr: 'Beom-joe', vn: 'Phạm tội' },
      { kr: '법률', pr: 'Beop-ryul', vn: 'Pháp luật' },
      { kr: '보관', pr: 'Bo-gwan', vn: 'Bảo quản' },
      { kr: '보호', pr: 'Bo-ho', vn: 'Bảo hộ' },
      { kr: '복잡', pr: 'Bok-jap', vn: 'Phức tạp' },
      { kr: '불만', pr: 'Bul-man', vn: 'Bất mãn' },
      { kr: '비밀', pr: 'Bi-mil', vn: 'Bí mật' },
      { kr: '사과', pr: 'Sa-gwa', vn: 'Tạ lỗi / Xin lỗi' },
      { kr: '사회', pr: 'Sa-hoe', vn: 'Xã hội' },
      { kr: '설명', pr: 'Seol-myeong', vn: 'Thuyết minh / Giải thích' },
      { kr: '성공', pr: 'Seong-gong', vn: 'Thành công' },
      { kr: '실수', pr: 'Sil-su', vn: 'Thất thủ / Sai lầm' },
      { kr: '안심', pr: 'An-sim', vn: 'An tâm' },
      { kr: '약속', pr: 'Yak-sok', vn: 'Ước thúc / Lời hứa' },
      { kr: '연락', pr: 'Yeon-rak', vn: 'Liên lạc' },
      { kr: '연습', pr: 'Yeon-seup', vn: 'Luyện tập' },
      { kr: '예감', pr: 'Ye-gam', vn: 'Dự cảm' },
      { kr: '완성', pr: 'Wan-seong', vn: 'Hoàn thành' },
      { kr: '요구', pr: 'Yo-gu', vn: 'Yêu cầu' },
      { kr: '용기', pr: 'Yong-gi', vn: 'Dũng khí' },
      { kr: '위기', pr: 'Wi-gi', vn: 'Nguy cơ' },
      { kr: '위험', pr: 'Wi-heom', vn: 'Nguy hiểm' },
      { kr: '이익', pr: 'I-ik', vn: 'Lợi ích' },
      { kr: '인간', pr: 'In-gan', vn: 'Nhân gian / Con người' },
    ],
  },
  {
    id: 16,
    title: '16) 공장과 생산 2\n(Nhà máy & Sản xuất - EPS)',
    icon: '⚙️',
    words: [
      { kr: '기계', pr: 'Gi-gye', vn: 'Máy móc' },
      { kr: '스위치', pr: 'Seu-wi-chi', vn: 'Công tắc' },
      { kr: '버튼', pr: 'Beo-teun', vn: 'Nút bấm' },
      { kr: '플러그', pr: 'Peul-leo-geu', vn: 'Phích cắm' },
      { kr: '콘센트', pr: 'Kon-sen-teu', vn: 'Ổ cắm điện' },
      { kr: '용접', pr: 'Yong-jeop', vn: 'Hàn' },
      { kr: '밀링', pr: 'Mil-ring', vn: 'Máy phay' },
      { kr: '선반', pr: 'Seon-ban', vn: 'Máy tiện' },
      { kr: '조립', pr: 'Jo-rip', vn: 'Lắp ráp' },
      { kr: '분해', pr: 'Bun-hae', vn: 'Tháo dỡ' },
      { kr: '박스', pr: 'Bak-seu', vn: 'Hộp / Thùng' },
      { kr: '테이프', pr: 'Te-i-peu', vn: 'Băng dính' },
      { kr: '무게', pr: 'Mu-ge', vn: 'Trọng lượng' },
      { kr: '크기', pr: 'Keu-gi', vn: 'Kích thước' },
      { kr: '길이', pr: 'Gil-i', vn: 'Chiều dài' },
      { kr: '두께', pr: 'Du-kke', vn: 'Độ dày' },
      { kr: '불량', pr: 'Bul-ryang', vn: 'Lỗi / Kém chất lượng' },
      { kr: '불량품', pr: 'Bul-ryang-pum', vn: 'Hàng lỗi' },
      { kr: '합격', pr: 'Hap-gyeok', vn: 'Đạt yêu cầu' },
      { kr: '수리', pr: 'Su-ri', vn: 'Sửa chữa' },
      { kr: '검사', pr: 'Geom-sa', vn: 'Kiểm tra' },
      { kr: '안전', pr: 'An-jeon', vn: 'An toàn' },
      { kr: '사고', pr: 'Sa-go', vn: 'Tai nạn' },
      { kr: '예방', pr: 'Ye-bang', vn: 'Phòng ngừa' },
      { kr: '주의', pr: 'Ju-ui', vn: 'Chú ý' },
      { kr: '경고', pr: 'Gyeong-go', vn: 'Cảnh báo' },
      { kr: '확인', pr: 'Hwak-in', vn: 'Xác nhận' },
      { kr: '보고', pr: 'Bo-go', vn: 'Báo cáo' },
      { kr: '지시', pr: 'Ji-si', vn: 'Chỉ thị' },
      { kr: '금지', pr: 'Geum-ji', vn: 'Cấm' },
      { kr: '허가', pr: 'Heo-ga', vn: 'Cho phép' },
      { kr: '작업복', pr: 'Jak-eop-bok', vn: 'Đồng phục làm việc' },
      { kr: '안전모', pr: 'An-jeon-mo', vn: 'Mũ bảo hộ' },
      { kr: '안전화', pr: 'An-jeon-hwa', vn: 'Giày bảo hộ' },
      { kr: '장갑', pr: 'Jang-gap', vn: 'Găng tay' },
      { kr: '마스크', pr: 'Ma-seu-keu', vn: 'Khẩu trang' },
      { kr: '보호구', pr: 'Bo-ho-gu', vn: 'Đồ bảo hộ' },
      { kr: '창고', pr: 'Chang-go', vn: 'Nhà kho' },
      { kr: '재고', pr: 'Jae-go', vn: 'Hàng tồn kho' },
      { kr: '물품', pr: 'Mul-pum', vn: 'Vật phẩm' },
      { kr: '납품', pr: 'Nap-pum', vn: 'Giao hàng' },
      { kr: '출고', pr: 'Chul-go', vn: 'Xuất kho' },
      { kr: '입고', pr: 'Ip-go', vn: 'Nhập kho' },
      { kr: '정리', pr: 'Jeong-ri', vn: 'Sắp xếp' },
      { kr: '정돈', pr: 'Jeong-don', vn: 'Chỉnh đốn' },
      { kr: '청소', pr: 'Cheong-so', vn: 'Dọn dẹp' },
      { kr: '관리', pr: 'Gwan-ri', vn: 'Quản lý' },
      { kr: '작업', pr: 'Jak-eop', vn: 'Thao tác / Làm việc' },
      { kr: '공장', pr: 'Gong-jang', vn: 'Nhà máy' },
      { kr: '생산', pr: 'Saeng-san', vn: 'Sản xuất' },
    ],
  },
  {
    id: 17,
    title: '17) 부사와 접속사\n(Phó từ & Liên từ)',
    icon: '🔗',
    words: [
      { kr: '그리고', pr: 'Geu-ri-go', vn: 'Và' },
      { kr: '그래서', pr: 'Geu-rae-seo', vn: 'Vì vậy' },
      { kr: '그러나', pr: 'Geu-reo-na', vn: 'Tuy nhiên' },
      { kr: '그런데', pr: 'Geu-reon-de', vn: 'Nhưng mà / Tiện thể' },
      { kr: '그러면', pr: 'Geu-reo-myeon', vn: 'Nếu vậy thì' },
      { kr: '하지만', pr: 'Ha-ji-man', vn: 'Nhưng' },
      { kr: '그렇지만', pr: 'Geu-reot-ji-man', vn: 'Mặc dù vậy' },
      { kr: '또는', pr: 'Tto-neun', vn: 'Hoặc là' },
      { kr: '아니면', pr: 'A-ni-myeon', vn: 'Hoặc' },
      { kr: '왜냐하면', pr: 'Wae-nya-ha-myeon', vn: 'Bởi vì' },
      { kr: '만약', pr: 'Man-yak', vn: 'Giả sử / Nếu' },
      { kr: '만일', pr: 'Man-il', vn: 'Vạn nhất / Nếu như' },
      { kr: '아주', pr: 'A-ju', vn: 'Rất' },
      { kr: '매우', pr: 'Mae-u', vn: 'Rất' },
      { kr: '너무', pr: 'Neo-mu', vn: 'Quá' },
      { kr: '진짜', pr: 'Jin-jja', vn: 'Thật sự' },
      { kr: '정말', pr: 'Jeong-mal', vn: 'Thật sự' },
      { kr: '참', pr: 'Cham', vn: 'Thật là' },
      { kr: '가장', pr: 'Ga-jang', vn: 'Nhất' },
      { kr: '제일', pr: 'Je-il', vn: 'Thứ nhất' },
      { kr: '조금', pr: 'Jo-geum', vn: 'Một chút' },
      { kr: '약간', pr: 'Yak-gan', vn: 'Hơi / Một ít' },
      { kr: '많이', pr: 'Man-i', vn: 'Nhiều' },
      { kr: '전혀', pr: 'Jeon-hyeo', vn: 'Hoàn toàn không' },
      { kr: '별로', pr: 'Byeol-ro', vn: 'Không ... lắm' },
      { kr: '거의', pr: 'Geo-ui', vn: 'Hầu như' },
      { kr: '다', pr: 'Da', vn: 'Tất cả' },
      { kr: '모두', pr: 'Mo-du', vn: 'Toàn bộ' },
      { kr: '일찍', pr: 'Il-jjik', vn: 'Sớm' },
      { kr: '늦게', pr: 'Neut-ge', vn: 'Muộn' },
      { kr: '빨리', pr: 'Ppal-ri', vn: 'Nhanh lên' },
      { kr: '천천히', pr: 'Cheon-cheon-hi', vn: 'Từ từ' },
      { kr: '곧', pr: 'Got', vn: 'Sắp / Ngay' },
      { kr: '금방', pr: 'Geum-bang', vn: 'Chốc lát / Vừa mới' },
      { kr: '방금', pr: 'Bang-geum', vn: 'Vừa lúc nãy' },
      { kr: '아까', pr: 'A-kka', vn: 'Lúc nãy' },
      { kr: '나중에', pr: 'Na-jung-e', vn: 'Sau này' },
      { kr: '이따가', pr: 'I-tta-ga', vn: 'Lát nữa' },
      { kr: '항상', pr: 'Hang-sang', vn: 'Luôn luôn' },
      { kr: '늘', pr: 'Neul', vn: 'Luôn luôn' },
      { kr: '언제나', pr: 'Eon-je-na', vn: 'Bất cứ lúc nào' },
      { kr: '가끔', pr: 'Ga-kkeum', vn: 'Thỉnh thoảng' },
      { kr: '종종', pr: 'Jong-jong', vn: 'Thi thoảng' },
      { kr: '자주', pr: 'Ja-ju', vn: 'Thường xuyên' },
      { kr: '먼저', pr: 'Meon-jeo', vn: 'Trước' },
      { kr: '우선', pr: 'U-seon', vn: 'Đầu tiên' },
      { kr: '혼자', pr: 'Hon-ja', vn: 'Một mình' },
      { kr: '함께', pr: 'Ham-kke', vn: 'Cùng nhau' },
      { kr: '같이', pr: 'Ga-chi', vn: 'Cùng với' },
      { kr: '서로', pr: 'Seo-ro', vn: 'Lẫn nhau' },
    ],
  },
  {
    id: 18,
    title: '18) 집과 가사\n(Nhà cửa & Việc nhà)',
    icon: '🏠',
    words: [
      { kr: '집', pr: 'Jip', vn: 'Nhà' },
      { kr: '거실', pr: 'Geo-sil', vn: 'Phòng khách' },
      { kr: '방', pr: 'Bang', vn: 'Phòng' },
      { kr: '부엌', pr: 'Bu-eok', vn: 'Phòng bếp' },
      { kr: '화장실', pr: 'Hwa-jang-sil', vn: 'Nhà vệ sinh' },
      { kr: '베란다', pr: 'Be-ran-da', vn: 'Ban công' },
      { kr: '현관', pr: 'Hyeon-gwan', vn: 'Lối vào' },
      { kr: '마당', pr: 'Ma-dang', vn: 'Sân' },
      { kr: '지붕', pr: 'Ji-bung', vn: 'Mái nhà' },
      { kr: '창문', pr: 'Chang-mun', vn: 'Cửa sổ' },
      { kr: '문', pr: 'Mun', vn: 'Cửa ra vào' },
      { kr: '벽', pr: 'Byeok', vn: 'Bức tường' },
      { kr: '바닥', pr: 'Ba-dak', vn: 'Sàn nhà' },
      { kr: '천장', pr: 'Cheon-jang', vn: 'Trần nhà' },
      { kr: '가구', pr: 'Ga-gu', vn: 'Nội thất' },
      { kr: '소파', pr: 'So-pa', vn: 'Ghế sofa' },
      { kr: '침대', pr: 'Chim-dae', vn: 'Giường' },
      { kr: '의자', pr: 'Ui-ja', vn: 'Cái ghế' },
      { kr: '책상', pr: 'Chaek-sang', vn: 'Bàn học' },
      { kr: '옷장', pr: 'Ot-jang', vn: 'Tủ quần áo' },
      { kr: '서랍', pr: 'Seo-rap', vn: 'Ngăn kéo' },
      { kr: '책장', pr: 'Chaek-jang', vn: 'Giá sách' },
      { kr: '식탁', pr: 'Sik-tak', vn: 'Bàn ăn' },
      { kr: '신발장', pr: 'Sin-bal-jang', vn: 'Tủ giày' },
      { kr: '냉장고', pr: 'Naeng-jang-go', vn: 'Tủ lạnh' },
      { kr: '세탁기', pr: 'Se-tak-gi', vn: 'Máy giặt' },
      { kr: '청소기', pr: 'Cheong-so-gi', vn: 'Máy hút bụi' },
      { kr: '선풍기', pr: 'Seon-pung-gi', vn: 'Quạt máy' },
      { kr: '에어컨', pr: 'E-eo-keon', vn: 'Máy lạnh' },
      { kr: '난방', pr: 'Nan-bang', vn: 'Lò sưởi' },
      { kr: '보일러', pr: 'Bo-il-reo', vn: 'Bình nóng lạnh' },
      { kr: '텔레비전', pr: 'Tel-re-bi-jeon', vn: 'Tivi' },
      { kr: '컴퓨터', pr: 'Keom-pyu-teo', vn: 'Máy tính' },
      { kr: '거울', pr: 'Geo-ul', vn: 'Cái gương' },
      { kr: '이불', pr: 'I-bul', vn: 'Cái chăn' },
      { kr: '베개', pr: 'Be-gae', vn: 'Cái gối' },
      { kr: '쿠션', pr: 'Ku-syeon', vn: 'Gối tựa' },
      { kr: '쓰레기통', pr: 'Sseu-re-gi-tong', vn: 'Thùng rác' },
      { kr: '빗자루', pr: 'Bit-ja-ru', vn: 'Cái chổi' },
      { kr: '걸레', pr: 'Geol-re', vn: 'Giẻ lau' },
      { kr: '휴지', pr: 'Hyu-ji', vn: 'Giấy vệ sinh' },
      { kr: '세제', pr: 'Se-je', vn: 'Bột giặt' },
      { kr: '빨래', pr: 'Ppal-rae', vn: 'Giặt giũ' },
      { kr: '설거지', pr: 'Seol-geo-ji', vn: 'Rửa bát' },
      { kr: '청소', pr: 'Cheong-so', vn: 'Dọn dẹp' },
      { kr: '요리', pr: 'Yo-ri', vn: 'Nấu ăn' },
      { kr: '정리', pr: 'Jeong-ri', vn: 'Sắp xếp' },
      { kr: '쓰레기', pr: 'Sseu-re-gi', vn: 'Rác' },
      { kr: '분리수거', pr: 'Bun-ri-su-geo', vn: 'Phân loại rác' },
      { kr: '버리다', pr: 'Beo-ri-da', vn: 'Vứt / Bỏ' },
    ],
  },
  {
    id: 19,
    title: '19) 스마트폰과 인터넷\n(Điện thoại & Mạng xã hội)',
    icon: '📱',
    words: [
      { kr: '스마트폰', pr: 'Seu-ma-teu-pon', vn: 'Điện thoại thông minh' },
      { kr: '휴대폰', pr: 'Hyu-dae-pon', vn: 'Điện thoại di động' },
      { kr: '전화', pr: 'Jeon-hwa', vn: 'Cuộc gọi' },
      { kr: '문자', pr: 'Mun-ja', vn: 'Tin nhắn văn bản' },
      { kr: '메시지', pr: 'Me-si-ji', vn: 'Tin nhắn' },
      { kr: '카카오톡', pr: 'Ka-ka-o-tok', vn: 'Kakaotalk' },
      { kr: '인터넷', pr: 'In-teo-net', vn: 'Internet' },
      { kr: '와이파이', pr: 'Wa-i-pa-i', vn: 'Wifi' },
      { kr: '데이터', pr: 'De-i-teo', vn: 'Dữ liệu di động' },
      { kr: '앱', pr: 'Aep', vn: 'Ứng dụng' },
      { kr: '어플', pr: 'Eo-peul', vn: 'Ứng dụng' },
      { kr: '다운로드', pr: 'Da-un-ro-deu', vn: 'Tải xuống' },
      { kr: '설치', pr: 'Seol-chi', vn: 'Cài đặt' },
      { kr: '삭제', pr: 'Sak-je', vn: 'Xóa' },
      { kr: '업데이트', pr: 'Eop-de-i-teu', vn: 'Cập nhật' },
      { kr: '비밀번호', pr: 'Bi-mil-beon-ho', vn: 'Mật khẩu' },
      { kr: '아이디', pr: 'A-i-di', vn: 'Tài khoản' },
      { kr: '로그인', pr: 'Ro-geu-in', vn: 'Đăng nhập' },
      { kr: '로그아웃', pr: 'Ro-geu-a-ut', vn: 'Đăng xuất' },
      { kr: '화면', pr: 'Hwa-myeon', vn: 'Màn hình' },
      { kr: '버튼', pr: 'Beo-teun', vn: 'Nút bấm' },
      { kr: '배터리', pr: 'Bae-teo-ri', vn: 'Pin' },
      { kr: '충전기', pr: 'Chung-jeon-gi', vn: 'Cục sạc' },
      { kr: '케이블', pr: 'Ke-i-beul', vn: 'Dây cáp' },
      { kr: '사진', pr: 'Sa-jin', vn: 'Hình ảnh' },
      { kr: '동영상', pr: 'Dong-yeong-sang', vn: 'Video' },
      { kr: '녹음', pr: 'Nok-eum', vn: 'Ghi âm' },
      { kr: '카메라', pr: 'Ka-me-ra', vn: 'Máy ảnh' },
      { kr: '갤러리', pr: 'Gael-leo-ri', vn: 'Bộ sưu tập ảnh' },
      { kr: '알림', pr: 'Al-rim', vn: 'Thông báo' },
      { kr: '소리', pr: 'So-ri', vn: 'Âm thanh' },
      { kr: '진동', pr: 'Jin-dong', vn: 'Rung' },
      { kr: '무음', pr: 'Mu-eum', vn: 'Im lặng' },
      { kr: '검색', pr: 'Geom-saek', vn: 'Tìm kiếm' },
      { kr: '복사', pr: 'Bok-sa', vn: 'Sao chép' },
      { kr: '붙여넣기', pr: 'But-yeo-neoh-gi', vn: 'Dán' },
      { kr: '공유', pr: 'Gong-yu', vn: 'Chia sẻ' },
      { kr: '링크', pr: 'Ring-keu', vn: 'Đường dẫn' },
      { kr: '사이트', pr: 'Sa-i-teu', vn: 'Trang web' },
      { kr: '주소', pr: 'Ju-so', vn: 'Địa chỉ' },
      { kr: '게임', pr: 'Ge-im', vn: 'Trò chơi' },
      { kr: '설정', pr: 'Seol-jeong', vn: 'Cài đặt' },
      { kr: '계정', pr: 'Gye-jeong', vn: 'Tài khoản' },
      { kr: '프로필', pr: 'Peu-ro-pil', vn: 'Hồ sơ cá nhân' },
      { kr: '차단', pr: 'Cha-dan', vn: 'Chặn' },
      { kr: '친구추가', pr: 'Chin-gu-chu-ga', vn: 'Thêm bạn' },
      { kr: '팔로우', pr: 'Pal-ro-u', vn: 'Theo dõi' },
      { kr: '구독', pr: 'Gu-dok', vn: 'Đăng ký' },
      { kr: '좋아요', pr: 'Jo-a-yo', vn: 'Thích' },
      { kr: '댓글', pr: 'Daet-geul', vn: 'Bình luận' },
    ],
  },
  {
    id: 20,
    title: '20) 마법 단어 3 - 발음 유사\n(Từ Hán-Hàn giống nhau)',
    icon: '🔥',
    words: [
      { kr: '자연', pr: 'Ja-yeon', vn: 'Tự nhiên' },
      { kr: '자유', pr: 'Ja-yu', vn: 'Tự do' },
      { kr: '이유', pr: 'I-yu', vn: 'Lý do' },
      { kr: '안전', pr: 'An-jeon', vn: 'An toàn' },
      { kr: '안정', pr: 'An-jeong', vn: 'An định / Ổn định' },
      { kr: '시민', pr: 'Si-min', vn: 'Thị dân / Công dân' },
      { kr: '시간', pr: 'Si-gan', vn: 'Thời gian' },
      { kr: '시대', pr: 'Si-dae', vn: 'Thời đại' },
      { kr: '시험', pr: 'Si-heom', vn: 'Thi nghiệm / Bài thi' },
      { kr: '실패', pr: 'Sil-pae', vn: 'Thất bại' },
      { kr: '실망', pr: 'Sil-mang', vn: 'Thất vọng' },
      { kr: '실업', pr: 'Sil-eop', vn: 'Thất nghiệp' },
      { kr: '심리', pr: 'Sim-ri', vn: 'Tâm lý' },
      { kr: '심장', pr: 'Sim-jang', vn: 'Tâm tạng / Trái tim' },
      { kr: '악몽', pr: 'Ak-mong', vn: 'Ác mộng' },
      { kr: '악기', pr: 'Ak-gi', vn: 'Nhạc khí / Nhạc cụ' },
      { kr: '약점', pr: 'Yak-jeom', vn: 'Nhược điểm' },
      { kr: '영웅', pr: 'Yeong-ung', vn: 'Anh hùng' },
      { kr: '영원', pr: 'Yeong-won', vn: 'Vĩnh viễn' },
      { kr: '운명', pr: 'Un-myeong', vn: 'Vận mệnh' },
      { kr: '위험', pr: 'Wi-heom', vn: 'Nguy hiểm' },
      { kr: '위기', pr: 'Wi-gi', vn: 'Nguy cơ' },
      { kr: '위치', pr: 'Wi-chi', vn: 'Vị trí' },
      { kr: '유명', pr: 'Yu-myeong', vn: 'Hữu danh / Nổi tiếng' },
      { kr: '유리', pr: 'Yu-ri', vn: 'Hữu lý / Có lợi' },
      { kr: '유지', pr: 'Yu-ji', vn: 'Duy trì' },
      { kr: '은혜', pr: 'Eun-hye', vn: 'Ân huệ' },
      { kr: '음악', pr: 'Eum-ak', vn: 'Âm nhạc' },
      { kr: '의견', pr: 'Ui-gyeon', vn: 'Ý kiến' },
      { kr: '의미', pr: 'Ui-mi', vn: 'Ý nghĩa' },
      { kr: '의무', pr: 'Ui-mu', vn: 'Nghĩa vụ' },
      { kr: '의사', pr: 'Ui-sa', vn: 'Bác sĩ / Ý tứ' },
      { kr: '의심', pr: 'Ui-sim', vn: 'Nghi tâm / Nghi ngờ' },
      { kr: '인식', pr: 'In-sik', vn: 'Nhận thức' },
      { kr: '인정', pr: 'In-jeong', vn: 'Nhận định / Công nhận' },
      { kr: '인간', pr: 'In-gan', vn: 'Nhân gian / Con người' },
      { kr: '인격', pr: 'In-gyeok', vn: 'Nhân cách' },
      { kr: '인구', pr: 'In-gu', vn: 'Nhân khẩu / Dân số' },
      { kr: '인기', pr: 'In-gi', vn: 'Nhân khí / Phổ biến' },
      { kr: '인내', pr: 'In-nae', vn: 'Nhẫn nại' },
      { kr: '자격', pr: 'Ja-gyeok', vn: 'Tư cách' },
      { kr: '자료', pr: 'Ja-ryo', vn: 'Tài liệu' },
      { kr: '자본', pr: 'Ja-bon', vn: 'Tư bản / Tiền vốn' },
      { kr: '자산', pr: 'Ja-san', vn: 'Tài sản' },
      { kr: '자세', pr: 'Ja-se', vn: 'Tư thế' },
      { kr: '자신', pr: 'Ja-sin', vn: 'Tự thân / Tự tin' },
      { kr: '자존심', pr: 'Ja-jon-sim', vn: 'Tự tôn tâm / Lòng tự trọng' },
      { kr: '작업', pr: 'Jak-eop', vn: 'Tác nghiệp / Làm việc' },
      { kr: '작용', pr: 'Jak-yong', vn: 'Tác dụng' },
      { kr: '전통', pr: 'Jeon-tong', vn: 'Truyền thống' },
    ],
  },
  {
    id: 21,
    title: '21) 학교 생활 2\n(Trường học & Học tập 2)',
    icon: '🎒',
    words: [
      { kr: '입학', pr: 'Ip-hak', vn: 'Nhập học' },
      { kr: '방학', pr: 'Bang-hak', vn: 'Kỳ nghỉ' },
      { kr: '개학', pr: 'Gae-hak', vn: 'Khai giảng' },
      { kr: '시험', pr: 'Si-heom', vn: 'Kỳ thi' },
      { kr: '성적', pr: 'Seong-jeok', vn: 'Thành tích' },
      { kr: '점수', pr: 'Jeom-su', vn: 'Điểm số' },
      { kr: '장학금', pr: 'Jang-hak-geum', vn: 'Học bổng' },
      { kr: '교복', pr: 'Gyo-bok', vn: 'Đồng phục' },
      { kr: '시간표', pr: 'Si-gan-pyo', vn: 'Thời khóa biểu' },
      { kr: '과목', pr: 'Gwa-mok', vn: 'Môn học' },
      { kr: '숙제', pr: 'Suk-je', vn: 'Bài tập về nhà' },
      { kr: '예습', pr: 'Ye-seup', vn: 'Học trước bài mới' },
      { kr: '복습', pr: 'Bok-seup', vn: 'Ôn tập' },
      { kr: '질문', pr: 'Jil-mun', vn: 'Câu hỏi' },
      { kr: '대답', pr: 'Dae-dap', vn: 'Câu trả lời' },
      { kr: '사전', pr: 'Sa-jeon', vn: 'Từ điển' },
      { kr: '단어', pr: 'Dan-eo', vn: 'Từ vựng' },
      { kr: '문법', pr: 'Mun-beop', vn: 'Ngữ pháp' },
      { kr: '발음', pr: 'Bal-eum', vn: 'Phát âm' },
      { kr: '회화', pr: 'Hoe-hwa', vn: 'Hội thoại' },
      { kr: '쓰기', pr: 'Sseu-gi', vn: 'Kỹ năng viết' },
      { kr: '듣기', pr: 'Deut-gi', vn: 'Kỹ năng nghe' },
      { kr: '읽기', pr: 'Ik-gi', vn: 'Kỹ năng đọc' },
      { kr: '동아리', pr: 'Dong-a-ri', vn: 'Câu lạc bộ' },
      { kr: '선배', pr: 'Seon-bae', vn: 'Tiền bối' },
      { kr: '후배', pr: 'Hu-bae', vn: 'Hậu bối' },
      { kr: '동기', pr: 'Dong-gi', vn: 'Bạn đồng khóa' },
      { kr: '학년', pr: 'Hak-nyeon', vn: 'Năm học' },
      { kr: '반', pr: 'Ban', vn: 'Lớp học' },
      { kr: '칠판', pr: 'Chil-pan', vn: 'Bảng đen' },
      { kr: '분필', pr: 'Bun-pil', vn: 'Phấn viết' },
      { kr: '휴강', pr: 'Hyu-gang', vn: 'Nghỉ học' },
      { kr: '결석', pr: 'Gyeol-seok', vn: 'Vắng mặt' },
      { kr: '지각', pr: 'Ji-gak', vn: 'Đi trễ' },
      { kr: '출석', pr: 'Chul-seok', vn: 'Điểm danh' },
      { kr: '등록금', pr: 'Deung-rok-geum', vn: 'Học phí' },
      { kr: '원서', pr: 'Won-seo', vn: 'Đơn đăng ký' },
      { kr: '합격', pr: 'Hap-gyeok', vn: 'Thi đỗ' },
      { kr: '불합격', pr: 'Bul-hap-gyeok', vn: 'Thi trượt' },
      { kr: '전공', pr: 'Jeon-gong', vn: 'Chuyên ngành' },
      { kr: '교양', pr: 'Gyo-yang', vn: 'Môn đại cương' },
      { kr: '교수', pr: 'Gyo-su', vn: 'Giáo sư' },
      { kr: '강의', pr: 'Gang-ui', vn: 'Bài giảng' },
      { kr: '논문', pr: 'Non-mun', vn: 'Luận văn' },
      { kr: '발표', pr: 'Bal-pyo', vn: 'Thuyết trình' },
      { kr: '규칙', pr: 'Gyu-chik', vn: 'Quy tắc' },
      { kr: '연필', pr: 'Yeon-pil', vn: 'Bút chì' },
      { kr: '필통', pr: 'Pil-tong', vn: 'Hộp bút' },
      { kr: '볼펜', pr: 'Bol-pen', vn: 'Bút bi' },
      { kr: '가르치다', pr: 'Ga-reu-chi-da', vn: 'Dạy học' },
    ],
  },
  {
    id: 22,
    title: '22) 의복과 미용\n(Thời trang & Làm đẹp)',
    icon: '👗',
    words: [
      { kr: '유행', pr: 'Yu-haeng', vn: 'Mốt / Trào lưu' },
      { kr: '스타일', pr: 'Seu-ta-il', vn: 'Phong cách' },
      { kr: '디자인', pr: 'Di-ja-in', vn: 'Thiết kế' },
      { kr: '사이즈', pr: 'Sa-i-jeu', vn: 'Kích cỡ' },
      { kr: '입어보다', pr: 'Ip-eo-bo-da', vn: 'Mặc thử' },
      { kr: '신어보다', pr: 'Sin-eo-bo-da', vn: 'Đi thử' },
      { kr: '화장품', pr: 'Hwa-jang-pum', vn: 'Mỹ phẩm' },
      { kr: '립스틱', pr: 'Rip-seu-tik', vn: 'Son môi' },
      { kr: '향수', pr: 'Hyang-su', vn: 'Nước hoa' },
      { kr: '머리', pr: 'Meo-ri', vn: 'Tóc' },
      { kr: '자르다', pr: 'Ja-reu-da', vn: 'Cắt' },
      { kr: '파마', pr: 'Pa-ma', vn: 'Uốn tóc' },
      { kr: '염색', pr: 'Yeom-saek', vn: 'Nhuộm tóc' },
      { kr: '미용실', pr: 'Mi-yong-sil', vn: 'Tiệm làm tóc' },
      { kr: '세탁', pr: 'Se-tak', vn: 'Giặt giũ' },
      { kr: '다림질', pr: 'Da-rim-jil', vn: 'Là / Ủi' },
      { kr: '옷걸이', pr: 'Ot-geol-i', vn: 'Mắc áo' },
      { kr: '바지', pr: 'Ba-ji', vn: 'Quần' },
      { kr: '반바지', pr: 'Ban-ba-ji', vn: 'Quần đùi' },
      { kr: '청바지', pr: 'Cheong-ba-ji', vn: 'Quần bò' },
      { kr: '치마', pr: 'Chi-ma', vn: 'Váy' },
      { kr: '원피스', pr: 'Won-pi-seu', vn: 'Váy liền' },
      { kr: '셔츠', pr: 'Syeo-cheu', vn: 'Áo sơ mi' },
      { kr: '블라우스', pr: 'Beul-ra-u-seu', vn: 'Áo Blouse' },
      { kr: '자켓', pr: 'Ja-ket', vn: 'Áo khoác ngắn' },
      { kr: '코트', pr: 'Ko-teu', vn: 'Áo khoác dài' },
      { kr: '패딩', pr: 'Pae-ding', vn: 'Áo phao' },
      { kr: '속옷', pr: 'Sok-ot', vn: 'Đồ lót' },
      { kr: '양말', pr: 'Yang-mal', vn: 'Tất / Vớ' },
      { kr: '스타킹', pr: 'Seu-ta-king', vn: 'Quần tất' },
      { kr: '신발', pr: 'Sin-bal', vn: 'Giày dép' },
      { kr: '구두', pr: 'Gu-du', vn: 'Giày da' },
      { kr: '운동화', pr: 'Un-dong-hwa', vn: 'Giày thể thao' },
      { kr: '슬리퍼', pr: 'Seul-ri-peo', vn: 'Dép lê' },
      { kr: '부츠', pr: 'Bu-cheu', vn: 'Giày bốt' },
      { kr: '장화', pr: 'Jang-hwa', vn: 'Ủng đi mưa' },
      { kr: '가방', pr: 'Ga-bang', vn: 'Túi xách' },
      { kr: '지갑', pr: 'Ji-gap', vn: 'Ví tiền' },
      { kr: '배낭', pr: 'Bae-nang', vn: 'Balo' },
      { kr: '모자', pr: 'Mo-ja', vn: 'Mũ / Nón' },
      { kr: '목도리', pr: 'Mok-do-ri', vn: 'Khăn quàng cổ' },
      { kr: '장갑', pr: 'Jang-gap', vn: 'Găng tay' },
      { kr: '안경', pr: 'An-gyeong', vn: 'Kính mắt' },
      { kr: '선글라스', pr: 'Seon-geul-ra-seu', vn: 'Kính râm' },
      { kr: '귀걸이', pr: 'Gwi-geol-i', vn: 'Hoa tai' },
      { kr: '목걸이', pr: 'Mok-geol-i', vn: 'Vòng cổ' },
      { kr: '반지', pr: 'Ban-ji', vn: 'Nhẫn' },
      { kr: '시계', pr: 'Si-gye', vn: 'Đồng hồ' },
      { kr: '팔찌', pr: 'Pal-jji', vn: 'Vòng tay' },
      { kr: '어울리다', pr: 'Eo-ul-ri-da', vn: 'Hợp / Vừa vặn' },
    ],
  },
  {
    id: 23,
    title: '23) 은행과 공공기관\n(Ngân hàng & Hành chính)',
    icon: '🏦',
    words: [
      { kr: '은행', pr: 'Eun-haeng', vn: 'Ngân hàng' },
      { kr: '창구', pr: 'Chang-gu', vn: 'Quầy giao dịch' },
      { kr: '번호표', pr: 'Beon-ho-pyo', vn: 'Phiếu lấy số' },
      { kr: '통장', pr: 'Tong-jang', vn: 'Sổ tiết kiệm' },
      { kr: '계좌', pr: 'Gye-jwa', vn: 'Tài khoản' },
      { kr: '비밀번호', pr: 'Bi-mil-beon-ho', vn: 'Mật khẩu' },
      { kr: '도장', pr: 'Do-jang', vn: 'Con dấu' },
      { kr: '신분증', pr: 'Sin-bun-jeung', vn: 'Thẻ căn cước' },
      { kr: '신용카드', pr: 'Sin-yong-ka-deu', vn: 'Thẻ tín dụng' },
      { kr: '체크카드', pr: 'Che-keu-ka-deu', vn: 'Thẻ ghi nợ' },
      { kr: '현금', pr: 'Hyeon-geum', vn: 'Tiền mặt' },
      { kr: '동전', pr: 'Dong-jeon', vn: 'Tiền xu' },
      { kr: '지폐', pr: 'Ji-pyeo', vn: 'Tiền giấy' },
      { kr: '수표', pr: 'Su-pyo', vn: 'Ngân phiếu' },
      { kr: '환전', pr: 'Hwan-jeon', vn: 'Đổi tiền' },
      { kr: '환율', pr: 'Hwan-yul', vn: 'Tỷ giá hối đoái' },
      { kr: '입금', pr: 'Ip-geum', vn: 'Nạp tiền' },
      { kr: '출금', pr: 'Chul-geum', vn: 'Rút tiền' },
      { kr: '송금', pr: 'Song-geum', vn: 'Chuyển tiền' },
      { kr: '수수료', pr: 'Su-su-ryo', vn: 'Lệ phí' },
      { kr: '대출', pr: 'Dae-chul', vn: 'Cho vay' },
      { kr: '이자', pr: 'I-ja', vn: 'Tiền lãi' },
      { kr: '저금', pr: 'Jeo-geum', vn: 'Tiết kiệm tiền' },
      { kr: '우체국', pr: 'U-che-guk', vn: 'Bưu điện' },
      { kr: '편지', pr: 'Pyeon-ji', vn: 'Thư' },
      { kr: '소포', pr: 'So-po', vn: 'Bưu kiện' },
      { kr: '택배', pr: 'Taek-bae', vn: 'Chuyển phát nhanh' },
      { kr: '우표', pr: 'U-pyo', vn: 'Tem' },
      { kr: '주소', pr: 'Ju-so', vn: 'Địa chỉ' },
      { kr: '우편번호', pr: 'U-pyeon-beon-ho', vn: 'Mã bưu điện' },
      { kr: '경찰서', pr: 'Gyeong-chal-seo', vn: 'Đồn cảnh sát' },
      { kr: '분실물', pr: 'Bun-sil-mul', vn: 'Đồ thất lạc' },
      { kr: '신고', pr: 'Sin-go', vn: 'Khai báo' },
      { kr: '소방서', pr: 'So-bang-seo', vn: 'Trạm cứu hỏa' },
      { kr: '구급차', pr: 'Gu-geup-cha', vn: 'Xe cấp cứu' },
      { kr: '대사관', pr: 'Dae-sa-gwan', vn: 'Đại sứ quán' },
      { kr: '비자', pr: 'Bi-ja', vn: 'Visa' },
      { kr: '여권', pr: 'Yeo-gwon', vn: 'Hộ chiếu' },
      { kr: '연장', pr: 'Yeon-jang', vn: 'Gia hạn' },
      { kr: '체류', pr: 'Che-ryu', vn: 'Lưu trú' },
      { kr: '출입국', pr: 'Chul-ip-guk', vn: 'Xuất nhập cảnh' },
      { kr: '주민센터', pr: 'Ju-min-sen-teo', vn: 'Ủy ban phường' },
      { kr: '증명서', pr: 'Jeung-myeong-seo', vn: 'Giấy chứng nhận' },
      { kr: '발급', pr: 'Bal-geup', vn: 'Cấp phát' },
      { kr: '서류', pr: 'Seo-ryu', vn: 'Tài liệu / Hồ sơ' },
      { kr: '복사', pr: 'Bok-sa', vn: 'Bản sao' },
      { kr: '서명', pr: 'Seo-myeong', vn: 'Ký tên' },
      { kr: '도서관', pr: 'Do-seo-gwan', vn: 'Thư viện' },
      { kr: '대출증', pr: 'Dae-chul-jeung', vn: 'Thẻ thư viện' },
      { kr: '반납', pr: 'Ban-nap', vn: 'Trả lại' },
    ],
  },
  {
    id: 24,
    title: '24) 성격과 감정표현\n(Tính cách & Cảm xúc)',
    icon: '🎭',
    words: [
      { kr: '성격', pr: 'Seong-gyeok', vn: 'Tính cách' },
      { kr: '착하다', pr: 'Chak-ha-da', vn: 'Hiền lành' },
      { kr: '나쁘다', pr: 'Na-ppeu-da', vn: 'Xấu / Tồi' },
      { kr: '조용하다', pr: 'Jo-yong-ha-da', vn: 'Trầm tính' },
      { kr: '활발하다', pr: 'Hwal-bal-ha-da', vn: 'Hoạt bát' },
      { kr: '급하다', pr: 'Geup-ha-da', vn: 'Nóng vội' },
      { kr: '느긋하다', pr: 'Neu-geut-ha-da', vn: 'Thong thả' },
      { kr: '꼼꼼하다', pr: 'Kkom-kkom-ha-da', vn: 'Tỉ mỉ' },
      { kr: '덜렁거리다', pr: 'Deol-reong-geo-ri-da', vn: 'Hậu đậu' },
      { kr: '친절하다', pr: 'Chin-jeol-ha-da', vn: 'Thân thiện' },
      { kr: '불친절하다', pr: 'Bul-chin-jeol-ha-da', vn: 'Không thân thiện' },
      { kr: '따뜻하다', pr: 'Tta-tteut-ha-da', vn: 'Ấm áp (Tính cách)' },
      { kr: '차갑다', pr: 'Cha-gap-da', vn: 'Lạnh lùng' },
      { kr: '부지런하다', pr: 'Bu-ji-reon-ha-da', vn: 'Chăm chỉ' },
      { kr: '게으르다', pr: 'Ge-eu-reu-da', vn: 'Lười biếng' },
      { kr: '정직하다', pr: 'Jeong-jik-ha-da', vn: 'Chính trực' },
      { kr: '거짓말', pr: 'Geo-jit-mal', vn: 'Lời nói dối' },
      { kr: '솔직하다', pr: 'Sol-jik-ha-da', vn: 'Thẳng thắn' },
      { kr: '똑똑하다', pr: 'Ttok-ttok-ha-da', vn: 'Thông minh' },
      { kr: '멍청하다', pr: 'Meong-cheong-ha-da', vn: 'Ngốc nghếch' },
      { kr: '겸손하다', pr: 'Gyeom-son-ha-da', vn: 'Khiêm tốn' },
      { kr: '거만하다', pr: 'Geo-man-ha-da', vn: 'Kiêu ngạo' },
      { kr: '고집', pr: 'Go-jip', vn: 'Sự bướng bỉnh' },
      { kr: '욕심', pr: 'Yok-sim', vn: 'Sự tham lam' },
      { kr: '이기적이다', pr: 'I-gi-jeok-i-da', vn: 'Ích kỷ' },
      { kr: '배려하다', pr: 'Bae-ryeo-ha-da', vn: 'Chu đáo' },
      { kr: '이해하다', pr: 'I-hae-ha-da', vn: 'Hiểu' },
      { kr: '참다', pr: 'Cham-da', vn: 'Chịu đựng' },
      { kr: '화내다', pr: 'Hwa-nae-da', vn: 'Tức giận' },
      { kr: '웃다', pr: 'Ut-da', vn: 'Cười' },
      { kr: '울다', pr: 'Ul-da', vn: 'Khóc' },
      { kr: '우울하다', pr: 'U-ul-ha-da', vn: 'U uất / Trầm cảm' },
      { kr: '외롭다', pr: 'Oe-rop-da', vn: 'Cô đơn' },
      { kr: '심심하다', pr: 'Sim-sim-ha-da', vn: 'Buồn chán' },
      { kr: '지루하다', pr: 'Ji-ru-ha-da', vn: 'Tẻ nhạt' },
      { kr: '귀찮다', pr: 'Gwi-chan-ta', vn: 'Phiền phức' },
      { kr: '부끄럽다', pr: 'Bu-kkeu-reop-da', vn: 'Ngại ngùng' },
      { kr: '창피하다', pr: 'Chang-pi-ha-da', vn: 'Xấu hổ' },
      { kr: '당당하다', pr: 'Dang-dang-ha-da', vn: 'Đường hoàng' },
      { kr: '자신감', pr: 'Ja-sin-gam', vn: 'Sự tự tin' },
      { kr: '용기', pr: 'Yong-gi', vn: 'Lòng dũng cảm' },
      { kr: '소심하다', pr: 'So-sim-ha-da', vn: 'Nhút nhát' },
      { kr: '적극적이다', pr: 'Jeok-geuk-jeok-i-da', vn: 'Tích cực' },
      { kr: '소극적이다', pr: 'So-geuk-jeok-i-da', vn: 'Tiêu cực' },
      { kr: '긍정적이다', pr: 'Geung-jeong-jeok-i-da', vn: 'Lạc quan' },
      { kr: '부정적이다', pr: 'Bu-jeong-jeok-i-da', vn: 'Bi quan' },
      { kr: '진지하다', pr: 'Jin-ji-ha-da', vn: 'Nghiêm túc' },
      { kr: '가볍다', pr: 'Ga-byeop-da', vn: 'Nông nổi' },
      { kr: '성실하다', pr: 'Seong-sil-ha-da', vn: 'Thành thực' },
      { kr: '무책임하다', pr: 'Mu-chaek-im-ha-da', vn: 'Vô trách nhiệm' },
    ],
  },
  {
    id: 25,
    title: '25) 마법 단어 4 - 발음 유사\n(Từ Hán-Hàn giống nhau)',
    icon: '🔮',
    words: [
      { kr: '회의', pr: 'Hoe-ui', vn: 'Hội nghị' },
      { kr: '의미', pr: 'Ui-mi', vn: 'Ý nghĩa' },
      { kr: '의사', pr: 'Ui-sa', vn: 'Bác sĩ / Ý tứ' },
      { kr: '의견', pr: 'Ui-gyeon', vn: 'Ý kiến' },
      { kr: '의심', pr: 'Ui-sim', vn: 'Nghi tâm / Nghi ngờ' },
      { kr: '의무', pr: 'Ui-mu', vn: 'Nghĩa vụ' },
      { kr: '의식', pr: 'Ui-sik', vn: 'Ý thức' },
      { kr: '생활', pr: 'Saeng-hwal', vn: 'Sinh hoạt' },
      { kr: '생명', pr: 'Saeng-myeong', vn: 'Sinh mệnh' },
      { kr: '생산', pr: 'Saeng-san', vn: 'Sản xuất' },
      { kr: '생물', pr: 'Saeng-mul', vn: 'Sinh vật' },
      { kr: '생존', pr: 'Saeng-jon', vn: 'Sinh tồn' },
      { kr: '활동', pr: 'Hwal-dong', vn: 'Hoạt động' },
      { kr: '활력', pr: 'Hwal-ryeok', vn: 'Hoạt lực' },
      { kr: '활용', pr: 'Hwal-yong', vn: 'Hoạt dụng / Sử dụng' },
      { kr: '확신', pr: 'Hwak-sin', vn: 'Xác tín' },
      { kr: '확인', pr: 'Hwak-in', vn: 'Xác nhận' },
      { kr: '환상', pr: 'Hwan-sang', vn: 'Ảo tưởng' },
      { kr: '환경', pr: 'Hwan-gyeong', vn: 'Hoàn cảnh / Môi trường' },
      { kr: '환영', pr: 'Hwan-yeong', vn: 'Hoan nghênh' },
      { kr: '감각', pr: 'Gam-gak', vn: 'Cảm giác' },
      { kr: '감정', pr: 'Gam-jeong', vn: 'Cảm tình' },
      { kr: '감사', pr: 'Gam-sa', vn: 'Cảm tạ' },
      { kr: '감소', pr: 'Gam-so', vn: 'Giảm thiểu' },
      { kr: '감염', pr: 'Gam-yeom', vn: 'Cảm nhiễm' },
      { kr: '공공', pr: 'Gong-gong', vn: 'Công cộng' },
      { kr: '공무원', pr: 'Gong-mu-won', vn: 'Công vụ viên' },
      { kr: '공사', pr: 'Gong-sa', vn: 'Công sự / Xây dựng' },
      { kr: '공식', pr: 'Gong-sik', vn: 'Công thức' },
      { kr: '공연', pr: 'Gong-yeon', vn: 'Công diễn' },
      { kr: '관리', pr: 'Gwan-ri', vn: 'Quản lý' },
      { kr: '관심', pr: 'Gwan-sim', vn: 'Quan tâm' },
      { kr: '관점', pr: 'Gwan-jeom', vn: 'Quan điểm' },
      { kr: '관객', pr: 'Gwan-gaek', vn: 'Quan khách' },
      { kr: '관찰', pr: 'Gwan-chal', vn: 'Quan sát' },
      { kr: '광고', pr: 'Gwang-go', vn: 'Quảng cáo' },
      { kr: '광장', pr: 'Gwang-jang', vn: 'Quảng trường' },
      { kr: '교육', pr: 'Gyo-yuk', vn: 'Giáo dục' },
      { kr: '교사', pr: 'Gyo-sa', vn: 'Giáo viên' },
      { kr: '교실', pr: 'Gyo-sil', vn: 'Giáo thất / Phòng học' },
      { kr: '교통', pr: 'Gyo-tong', vn: 'Giao thông' },
      { kr: '교환', pr: 'Gyo-hwan', vn: 'Giao hoán' },
      { kr: '구역', pr: 'Gu-yeok', vn: 'Khu vực' },
      { kr: '구별', pr: 'Gu-byeol', vn: 'Khu biệt' },
      { kr: '구조', pr: 'Gu-jo', vn: 'Cấu tạo / Cứu trợ' },
      { kr: '국가', pr: 'Guk-ga', vn: 'Quốc gia' },
      { kr: '국적', pr: 'Guk-jeok', vn: 'Quốc tịch' },
      { kr: '국제', pr: 'Guk-je', vn: 'Quốc tế' },
      { kr: '독서', pr: 'Dok-seo', vn: 'Độc thư / Đọc sách' },
      { kr: '도서관', pr: 'Do-seo-gwan', vn: 'Đồ thư quán / Thư viện' },
    ],
  },
  {
    id: 26,
    title: '26) 요리와 식당\n(Nấu ăn & Nhà hàng)',
    icon: '🍳',
    words: [
      { kr: '식당', pr: 'Sik-dang', vn: 'Nhà hàng' },
      { kr: '메뉴판', pr: 'Me-nyu-pan', vn: 'Thực đơn' },
      { kr: '주문', pr: 'Ju-mun', vn: 'Gọi món' },
      { kr: '인분', pr: 'In-bun', vn: 'Suất' },
      { kr: '종업원', pr: 'Jong-eop-won', vn: 'Nhân viên phục vụ' },
      { kr: '손님', pr: 'Son-nim', vn: 'Khách hàng' },
      { kr: '계산', pr: 'Gye-san', vn: 'Thanh toán' },
      { kr: '영수증', pr: 'Yeong-su-jeung', vn: 'Hóa đơn' },
      { kr: '포장', pr: 'Po-jang', vn: 'Đóng gói' },
      { kr: '배달', pr: 'Bae-dal', vn: 'Giao hàng' },
      { kr: '요리', pr: 'Yo-ri', vn: 'Nấu ăn / Món ăn' },
      { kr: '재료', pr: 'Jae-ryo', vn: 'Nguyên liệu' },
      { kr: '끓이다', pr: 'Kkeul-i-da', vn: 'Đun sôi' },
      { kr: '삶다', pr: 'Sam-da', vn: 'Luộc' },
      { kr: '굽다', pr: 'Gup-da', vn: 'Nướng' },
      { kr: '볶다', pr: 'Bok-da', vn: 'Xào' },
      { kr: '튀기다', pr: 'Twi-gi-da', vn: 'Chiên' },
      { kr: '썰다', pr: 'Sseol-da', vn: 'Thái' },
      { kr: '자르다', pr: 'Ja-reu-da', vn: 'Cắt' },
      { kr: '섞다', pr: 'Seok-da', vn: 'Trộn' },
      { kr: '비비다', pr: 'Bi-bi-da', vn: 'Trộn đều' },
      { kr: '붓다', pr: 'But-da', vn: 'Đổ vào' },
      { kr: '찌다', pr: 'Jji-da', vn: 'Hấp' },
      { kr: '맛보다', pr: 'Mat-bo-da', vn: 'Nếm thử' },
      { kr: '숟가락', pr: 'Sut-ga-rak', vn: 'Thìa' },
      { kr: '젓가락', pr: 'Jeot-ga-rak', vn: 'Đũa' },
      { kr: '포크', pr: 'Po-keu', vn: 'Nĩa' },
      { kr: '나이프', pr: 'Na-i-peu', vn: 'Dao ăn' },
      { kr: '접시', pr: 'Jeop-si', vn: 'Cái đĩa' },
      { kr: '그릇', pr: 'Geu-reut', vn: 'Cái bát' },
      { kr: '컵', pr: 'Keop', vn: 'Cái cốc' },
      { kr: '냄비', pr: 'Naem-bi', vn: 'Cái nồi' },
      { kr: '프라이팬', pr: 'Peu-ra-i-paen', vn: 'Chảo rán' },
      { kr: '도마', pr: 'Do-ma', vn: 'Cái thớt' },
      { kr: '국자', pr: 'Guk-ja', vn: 'Môi múc canh' },
      { kr: '밥솥', pr: 'Bap-sot', vn: 'Nồi cơm điện' },
      { kr: '소금', pr: 'So-geum', vn: 'Muối' },
      { kr: '설탕', pr: 'Seol-tang', vn: 'Đường' },
      { kr: '간장', pr: 'Gan-jang', vn: 'Xì dầu' },
      { kr: '고추장', pr: 'Go-chu-jang', vn: 'Tương ớt' },
      { kr: '된장', pr: 'Doen-jang', vn: 'Tương đậu' },
      { kr: '식초', pr: 'Sik-cho', vn: 'Giấm' },
      { kr: '참기름', pr: 'Cham-gi-reum', vn: 'Dầu mè' },
      { kr: '마늘', pr: 'Ma-neul', vn: 'Tỏi' },
      { kr: '양파', pr: 'Yang-pa', vn: 'Hành tây' },
      { kr: '파', pr: 'Pa', vn: 'Hành lá' },
      { kr: '고추', pr: 'Go-chu', vn: 'Quả ớt' },
      { kr: '후추', pr: 'Hu-chu', vn: 'Hạt tiêu' },
      { kr: '깨', pr: 'Kkae', vn: 'Vừng' },
      { kr: '얼음', pr: 'Eol-eum', vn: 'Đá lạnh' },
    ],
  },
  {
    id: 27,
    title: '27) 연애와 결혼\n(Hẹn hò & Kết hôn)',
    icon: '💍',
    words: [
      { kr: '연애', pr: 'Yeon-ae', vn: 'Hẹn hò' },
      { kr: '사랑', pr: 'Sa-rang', vn: 'Tình yêu' },
      { kr: '이별', pr: 'I-byeol', vn: 'Sự chia ly' },
      { kr: '헤어지다', pr: 'He-eo-ji-da', vn: 'Chia tay' },
      { kr: '만나다', pr: 'Man-na-da', vn: 'Gặp gỡ' },
      { kr: '사귀다', pr: 'Sa-gwi-da', vn: 'Kết giao' },
      { kr: '소개팅', pr: 'So-gae-ting', vn: 'Buổi hẹn hò mù' },
      { kr: '선', pr: 'Seon', vn: 'Xem mắt' },
      { kr: '첫눈', pr: 'Cheot-nun', vn: 'Tuyết đầu mùa' },
      { kr: '반하다', pr: 'Ban-ha-da', vn: 'Phải lòng' },
      { kr: '고백하다', pr: 'Go-baek-ha-da', vn: 'Tỏ tình' },
      { kr: '데이트', pr: 'De-i-teu', vn: 'Buổi hẹn hò' },
      { kr: '약속', pr: 'Yak-sok', vn: 'Cuộc hẹn' },
      { kr: '선물', pr: 'Seon-mul', vn: 'Quà tặng' },
      { kr: '기념일', pr: 'Gi-nyeom-il', vn: 'Ngày kỷ niệm' },
      { kr: '백일', pr: 'Baek-il', vn: 'Kỷ niệm 100 ngày' },
      { kr: '반지', pr: 'Ban-ji', vn: 'Nhẫn' },
      { kr: '커플', pr: 'Keo-peul', vn: 'Cặp đôi' },
      { kr: '애인', pr: 'Ae-in', vn: 'Người yêu' },
      { kr: '남자친구', pr: 'Nam-ja-chin-gu', vn: 'Bạn trai' },
      { kr: '여자친구', pr: 'Yeo-ja-chin-gu', vn: 'Bạn gái' },
      { kr: '밀당', pr: 'Mil-dang', vn: 'Kéo đẩy' },
      { kr: '질투', pr: 'Jil-tu', vn: 'Ghen tuông' },
      { kr: '싸우다', pr: 'Ssa-u-da', vn: 'Cãi nhau' },
      { kr: '화해하다', pr: 'Hwa-hae-ha-da', vn: 'Làm hòa' },
      { kr: '용서하다', pr: 'Yong-seo-ha-da', vn: 'Tha thứ' },
      { kr: '뽀뽀', pr: 'Ppo-ppo', vn: 'Hôn nhẹ' },
      { kr: '키스', pr: 'Ki-seu', vn: 'Hôn sâu' },
      { kr: '안다', pr: 'An-da', vn: 'Ôm' },
      { kr: '손잡다', pr: 'Son-jap-da', vn: 'Nắm tay' },
      { kr: '프로포즈', pr: 'Peu-ro-po-jeu', vn: 'Cầu hôn' },
      { kr: '청혼', pr: 'Cheong-hon', vn: 'Cầu hôn' },
      { kr: '결혼', pr: 'Gyeol-hon', vn: 'Kết hôn' },
      { kr: '약혼', pr: 'Yak-hon', vn: 'Đính hôn' },
      { kr: '신랑', pr: 'Sin-rang', vn: 'Chú rể' },
      { kr: '신부', pr: 'Sin-bu', vn: 'Cô dâu' },
      { kr: '웨딩드레스', pr: 'We-ding-deu-re-seu', vn: 'Váy cưới' },
      { kr: '식장', pr: 'Sik-jang', vn: 'Lễ đường' },
      { kr: '부부', pr: 'Bu-bu', vn: 'Vợ chồng' },
      { kr: '신혼', pr: 'Sin-hon', vn: 'Tân hôn' },
      { kr: '부케', pr: 'Bu-ke', vn: 'Hoa cưới' },
      { kr: '축의금', pr: 'Chuk-ui-geum', vn: 'Tiền mừng cưới' },
      { kr: '하객', pr: 'Ha-gaek', vn: 'Khách dự tiệc' },
      { kr: '이혼', pr: 'I-hon', vn: 'Ly hôn' },
      { kr: '재혼', pr: 'Jae-hon', vn: 'Tái hôn' },
      { kr: '임신', pr: 'Im-sin', vn: 'Mang thai' },
      { kr: '출산', pr: 'Chul-san', vn: 'Sinh con' },
      { kr: '육아', pr: 'Yuk-a', vn: 'Nuôi dạy con' },
      { kr: '부모', pr: 'Bu-mo', vn: 'Bố mẹ' },
      { kr: '가정', pr: 'Ga-jeong', vn: 'Gia đình' },
    ],
  },
  {
    id: 28,
    title: '28) 사건과 사고\n(Tai nạn & Sự cố - EPS)',
    icon: '🚨',
    words: [
      { kr: '사건', pr: 'Sa-geon', vn: 'Sự kiện / Vụ án' },
      { kr: '사고', pr: 'Sa-go', vn: 'Tai nạn' },
      { kr: '발생하다', pr: 'Bal-saeng-ha-da', vn: 'Phát sinh' },
      { kr: '다치다', pr: 'Da-chi-da', vn: 'Bị thương' },
      { kr: '죽다', pr: 'Juk-da', vn: 'Chết' },
      { kr: '사망', pr: 'Sa-mang', vn: 'Tử vong' },
      { kr: '살인', pr: 'Sal-in', vn: 'Sát nhân' },
      { kr: '도둑', pr: 'Do-duk', vn: 'Kẻ trộm' },
      { kr: '도둑맞다', pr: 'Do-duk-mat-da', vn: 'Bị ăn trộm' },
      { kr: '훔치다', pr: 'Hum-chi-da', vn: 'Trộm cắp' },
      { kr: '소매치기', pr: 'So-mae-chi-gi', vn: 'Móc túi' },
      { kr: '강도', pr: 'Gang-do', vn: 'Tên cướp' },
      { kr: '경찰', pr: 'Gyeong-chal', vn: 'Cảnh sát' },
      { kr: '형사', pr: 'Hyeong-sa', vn: 'Hình sự' },
      { kr: '체포', pr: 'Che-po', vn: 'Bắt giữ' },
      { kr: '감옥', pr: 'Gam-ok', vn: 'Nhà tù' },
      { kr: '범인', pr: 'Beom-in', vn: 'Phạm nhân' },
      { kr: '범죄', pr: 'Beom-joe', vn: 'Tội ác' },
      { kr: '피해자', pr: 'Pi-hae-ja', vn: 'Người bị hại' },
      { kr: '가해자', pr: 'Ga-hae-ja', vn: 'Người gây hại' },
      { kr: '신고', pr: 'Sin-go', vn: 'Khai báo' },
      { kr: '112', pr: 'Il-il-i', vn: 'Cảnh sát (112)' },
      { kr: '119', pr: 'Il-il-gu', vn: 'Cấp cứu (119)' },
      { kr: '구급차', pr: 'Gu-geup-cha', vn: 'Xe cấp cứu' },
      { kr: '소방차', pr: 'So-bang-cha', vn: 'Xe cứu hỏa' },
      { kr: '화재', pr: 'Hwa-jae', vn: 'Hỏa hoạn' },
      { kr: '불', pr: 'Bul', vn: 'Lửa' },
      { kr: '끄다', pr: 'Kkeu-da', vn: 'Dập tắt' },
      { kr: '대피하다', pr: 'Dae-pi-ha-da', vn: 'Sơ tán' },
      { kr: '지진', pr: 'Ji-jin', vn: 'Động đất' },
      { kr: '홍수', pr: 'Hong-su', vn: 'Lũ lụt' },
      { kr: '태풍', pr: 'Tae-pung', vn: 'Bão' },
      { kr: '폭우', pr: 'Pok-u', vn: 'Mưa lớn' },
      { kr: '폭설', pr: 'Pok-seol', vn: 'Bão tuyết' },
      { kr: '피해', pr: 'Pi-hae', vn: 'Thiệt hại' },
      { kr: '보상', pr: 'Bo-sang', vn: 'Bồi thường' },
      { kr: '보험', pr: 'Bo-heom', vn: 'Bảo hiểm' },
      { kr: '합의', pr: 'Hap-ui', vn: 'Thỏa thuận' },
      { kr: '재난', pr: 'Jae-nan', vn: 'Thảm họa' },
      { kr: '구조', pr: 'Gu-jo', vn: 'Cứu hộ' },
      { kr: '구하다', pr: 'Gu-ha-da', vn: 'Cứu giúp' },
      { kr: '살리다', pr: 'Sal-ri-da', vn: 'Cứu sống' },
      { kr: '위험', pr: 'Wi-heom', vn: 'Nguy hiểm' },
      { kr: '안전', pr: 'An-jeon', vn: 'An toàn' },
      { kr: '조심', pr: 'Jo-sim', vn: 'Cẩn thận' },
      { kr: '경고', pr: 'Gyeong-go', vn: 'Cảnh báo' },
      { kr: '금지', pr: 'Geum-ji', vn: 'Cấm' },
      { kr: '주의', pr: 'Ju-ui', vn: 'Chú ý' },
      { kr: '벌금', pr: 'Beol-geum', vn: 'Tiền phạt' },
      { kr: '과태료', pr: 'Gwa-tae-ryo', vn: 'Tiền phạt hành chính' },
    ],
  },
  {
    id: 29,
    title: '29) 알바와 파트타임\n(Làm thêm & Part-time)',
    icon: '🏪',
    words: [
      { kr: '아르바이트', pr: 'A-reu-ba-i-teu', vn: 'Làm thêm' },
      { kr: '알바생', pr: 'Al-ba-saeng', vn: 'Nhân viên part-time' },
      { kr: '시급', pr: 'Si-geup', vn: 'Lương theo giờ' },
      { kr: '주휴수당', pr: 'Ju-hyu-su-dang', vn: 'Phụ cấp ngày nghỉ' },
      { kr: '야간수당', pr: 'Ya-gan-su-dang', vn: 'Phụ cấp làm đêm' },
      { kr: '출근', pr: 'Chul-geun', vn: 'Đi làm' },
      { kr: '퇴근', pr: 'Toe-geun', vn: 'Tan làm' },
      { kr: '교대', pr: 'Gyo-dae', vn: 'Giao ca' },
      { kr: '편의점', pr: 'Pyeon-ui-jeom', vn: 'Cửa hàng tiện lợi' },
      { kr: '식당', pr: 'Sik-dang', vn: 'Nhà hàng' },
      { kr: '서빙', pr: 'Seo-bing', vn: 'Phục vụ' },
      { kr: '손님', pr: 'Son-nim', vn: 'Khách hàng' },
      { kr: '단골', pr: 'Dan-gol', vn: 'Khách quen' },
      { kr: '어서오세요', pr: 'Eo-seo-o-se-yo', vn: 'Xin chào quý khách' },
      {
        kr: '안녕히가세요',
        pr: 'An-nyeong-hi-ga-se-yo',
        vn: 'Tạm biệt quý khách',
      },
      { kr: '주문', pr: 'Ju-mun', vn: 'Gọi món' },
      { kr: '계산', pr: 'Gye-san', vn: 'Thanh toán' },
      { kr: '포스기', pr: 'Po-seu-gi', vn: 'Máy tính tiền' },
      { kr: '바코드', pr: 'Ba-ko-deu', vn: 'Mã vạch' },
      { kr: '찍다', pr: 'Jjik-da', vn: 'Quét mã' },
      { kr: '카드', pr: 'Ka-deu', vn: 'Thẻ' },
      { kr: '현금', pr: 'Hyeon-geum', vn: 'Tiền mặt' },
      { kr: '거스름돈', pr: 'Geo-seu-reum-don', vn: 'Tiền thừa' },
      { kr: '영수증', pr: 'Yeong-su-jeung', vn: 'Hóa đơn' },
      { kr: '봉투', pr: 'Bong-tu', vn: 'Túi đựng' },
      { kr: '할인', pr: 'Hal-in', vn: 'Giảm giá' },
      { kr: '적립', pr: 'Jeok-rip', vn: 'Tích điểm' },
      { kr: '멤버십', pr: 'Mem-beo-sip', vn: 'Thẻ thành viên' },
      { kr: '교환', pr: 'Gyo-hwan', vn: 'Đổi hàng' },
      { kr: '환불', pr: 'Hwan-bul', vn: 'Hoàn tiền' },
      { kr: '데우다', pr: 'De-u-da', vn: 'Hâm nóng' },
      { kr: '유통기한', pr: 'Yu-tong-gi-han', vn: 'Hạn sử dụng' },
      { kr: '폐기', pr: 'Pye-gi', vn: 'Hàng hủy' },
      { kr: '재고', pr: 'Jae-go', vn: 'Hàng tồn kho' },
      { kr: '채우다', pr: 'Chae-u-da', vn: 'Lấp đầy' },
      { kr: '진열하다', pr: 'Jin-yeol-ha-da', vn: 'Trưng bày' },
      { kr: '물건', pr: 'Mul-geon', vn: 'Hàng hóa' },
      { kr: '창고', pr: 'Chang-go', vn: 'Nhà kho' },
      { kr: '사장님', pr: 'Sa-jang-nim', vn: 'Giám đốc' },
      { kr: '점장님', pr: 'Jeom-jang-nim', vn: 'Cửa hàng trưởng' },
      { kr: '매니저', pr: 'Mae-ni-jeo', vn: 'Quản lý' },
      { kr: '동료', pr: 'Dong-ryo', vn: 'Đồng nghiệp' },
      { kr: '보건증', pr: 'Bo-geon-jeung', vn: 'Giấy khám sức khỏe' },
      { kr: '이력서', pr: 'I-ryeok-seo', vn: 'Sơ yếu lý lịch' },
      { kr: '면접', pr: 'Myeon-jeop', vn: 'Phỏng vấn' },
      { kr: '유니폼', pr: 'Yu-ni-pom', vn: 'Đồng phục' },
      { kr: '앞치마', pr: 'Ap-chi-ma', vn: 'Tạp dề' },
      { kr: '명찰', pr: 'Myeong-chal', vn: 'Bảng tên' },
      { kr: '청소', pr: 'Cheong-so', vn: 'Dọn dẹp' },
      { kr: '쓰레기통', pr: 'Sseu-re-gi-tong', vn: 'Thùng rác' },
    ],
  },
  {
    id: 30,
    title: '30) 마법 단어 5 - 발음 유사\n(Từ Hán-Hàn giống nhau)',
    icon: '👑',
    words: [
      { kr: '기사', pr: 'Gi-sa', vn: 'Ký sự / Báo chí' },
      { kr: '기분', pr: 'Gi-bun', vn: 'Khí phân / Tâm trạng' },
      { kr: '기념', pr: 'Gi-nyeom', vn: 'Kỷ niệm' },
      { kr: '기술', pr: 'Gi-sul', vn: 'Kỹ thuật' },
      { kr: '기억', pr: 'Gi-eok', vn: 'Ký ức' },
      { kr: '기관', pr: 'Gi-gwan', vn: 'Cơ quan' },
      { kr: '기운', pr: 'Gi-un', vn: 'Khí vận' },
      { kr: '기원', pr: 'Gi-won', vn: 'Kỷ nguyên' },
      { kr: '기호', pr: 'Gi-ho', vn: 'Ký hiệu' },
      { kr: '노동', pr: 'No-dong', vn: 'Lao động' },
      { kr: '노력', pr: 'No-ryeok', vn: 'Nỗ lực' },
      { kr: '농민', pr: 'Nong-min', vn: 'Nông dân' },
      { kr: '능력', pr: 'Neung-ryeok', vn: 'Năng lực' },
      { kr: '단체', pr: 'Dan-che', vn: 'Đoàn thể' },
      { kr: '대륙', pr: 'Dae-ryuk', vn: 'Đại lục' },
      { kr: '대중', pr: 'Dae-jung', vn: 'Đại chúng' },
      { kr: '대학', pr: 'Dae-hak', vn: 'Đại học' },
      { kr: '도시', pr: 'Do-si', vn: 'Đô thị' },
      { kr: '독재', pr: 'Dok-jae', vn: 'Độc tài' },
      { kr: '독립', pr: 'Dok-rip', vn: 'Độc lập' },
      { kr: '동맹', pr: 'Dong-maeng', vn: 'Đồng minh' },
      { kr: '동물', pr: 'Dong-mul', vn: 'Động vật' },
      { kr: '동지', pr: 'Dong-ji', vn: 'Đồng chí' },
      { kr: '미묘', pr: 'Mi-myo', vn: 'Vi diệu' },
      { kr: '미소', pr: 'Mi-so', vn: 'Vi tiếu / Nụ cười' },
      { kr: '민주', pr: 'Min-ju', vn: 'Dân chủ' },
      { kr: '발전', pr: 'Bal-jeon', vn: 'Phát triển' },
      { kr: '발견', pr: 'Bal-gyeon', vn: 'Phát hiện' },
      { kr: '방식', pr: 'Bang-sik', vn: 'Phương thức' },
      { kr: '방향', pr: 'Bang-hyang', vn: 'Phương hướng' },
      { kr: '방해', pr: 'Bang-hae', vn: 'Phương hại' },
      { kr: '배우', pr: 'Bae-u', vn: 'Bài ưu / Diễn viên' },
      { kr: '병원', pr: 'Byeong-won', vn: 'Bệnh viện' },
      { kr: '보수', pr: 'Bo-su', vn: 'Bảo thủ' },
      { kr: '복잡', pr: 'Bok-jap', vn: 'Phức tạp' },
      { kr: '부자', pr: 'Bu-ja', vn: 'Phú tử / Người giàu' },
      { kr: '분석', pr: 'Bun-seok', vn: 'Phân tích' },
      { kr: '사상', pr: 'Sa-sang', vn: 'Tư tưởng' },
      { kr: '사업', pr: 'Sa-eop', vn: 'Sự nghiệp' },
      { kr: '사유', pr: 'Sa-yu', vn: 'Tư do / Lý do' },
      { kr: '사태', pr: 'Sa-tae', vn: 'Sự thái' },
      { kr: '사회', pr: 'Sa-hoe', vn: 'Xã hội' },
      { kr: '산업', pr: 'San-eop', vn: 'Sản nghiệp' },
      { kr: '생존', pr: 'Saeng-jon', vn: 'Sinh tồn' },
      { kr: '선언', pr: 'Seon-eon', vn: 'Tuyên ngôn' },
      { kr: '선택', pr: 'Seon-taek', vn: 'Tuyển trạch / Lựa chọn' },
      { kr: '식량', pr: 'Sik-ryang', vn: 'Lương thực' },
      { kr: '신념', pr: 'Sin-nyeom', vn: 'Tín niệm' },
      { kr: '신호', pr: 'Sin-ho', vn: 'Tín hiệu' },
      { kr: '자유', pr: 'Ja-yu', vn: 'Tự do' },
    ],
  },
];
